/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Node, Edge } from "@xyflow/react";

// ─── OLED pixel → MONO_HLSB bytes ─────────────────────────────────────────────
// The node stores pixels as boolean[][] with storedH rows (typically 32 for a
// 128×64 display). Each stored row doubles to fill the real OLED height.
function oledPixelsToMonoHLSB(pixels: boolean[][], oledW: number, oledH: number): Uint8Array {
  const storedH = pixels.length || 1;
  const bytesPerRow = Math.ceil(oledW / 8);
  const buf = new Uint8Array(bytesPerRow * oledH);
  for (let oledRow = 0; oledRow < oledH; oledRow++) {
    const srcRow = Math.min(Math.floor((oledRow / oledH) * storedH), storedH - 1);
    const row = pixels[srcRow] ?? [];
    for (let col = 0; col < oledW; col++) {
      if (row[col]) {
        const byteIdx = oledRow * bytesPerRow + Math.floor(col / 8);
        buf[byteIdx] |= (1 << (7 - (col % 8))); // MONO_HLSB: MSB = leftmost pixel
      }
    }
  }
  return buf;
}

function bytesToPyHex(buf: Uint8Array): string {
  return Array.from(buf).map(b => `\\x${b.toString(16).padStart(2, "0")}`).join("");
}

/**
 * Robust Graph Traversal Code Generator for Kakoon CodeLab.
 * Walks the connected flow starting from root nodes (unconnected/entry points),
 * recursing into loop body and conditional branches, and following sequence lines.
 */
export function generatePythonFromFlow(nodes: Node[], edges: Edge[]): string {
  if (nodes.length === 0) return "# Add nodes to generate code\n";

  const nodeMap = new Map<string, Node>();
  for (const n of nodes) nodeMap.set(n.id, n);

  // Use edges exactly as drawn — no flipping/normalization.
  // Users connect nodes in execution order; the direction is correct by design.

  // Root nodes = nodes that have no incoming flow edges
  // (ignore incoming "true"/"false"/"body" handle edges — those are branch entries, not sequential flow)
  const hasIncomingFlow = new Set<string>();
  for (const e of edges) {
    // An edge pointing INTO a node counts as "has incoming flow" only if it's
    // a plain sequential edge (not a body/true/false branch handle from a loop/conditional)
    const srcHandle = e.sourceHandle ?? "";
    if (srcHandle !== "body" && srcHandle !== "true" && srcHandle !== "false") {
      hasIncomingFlow.add(e.target);
    }
  }
  const rootNodes = nodes.filter((n) => !hasIncomingFlow.has(n.id));
  const sortedRoots = [...rootNodes].sort((a, b) => a.position.y - b.position.y);

  const lines: string[] = ["# Generated by Kakoon CodeLab Node Editor", ""];

  // Collect imports and setups
  const imports = new Set<string>();
  const setupLines: string[] = [];

  const visited = new Set<string>();

  // Loop types that use getLoopBodyLines for their body
  const LOOP_TYPES = ["forever_loop", "for_loop", "while_loop", "repeat"];

  /**
   * Returns the lines for the body of a loop / if-else node.
   *
   * Strategy (in order):
   * 1. If one or more "body" handle edges exist, follow each chain in Y order.
   * 2. Otherwise, collect EVERY directly-connected node below the loop (by Y),
   *    sort them by Y, and generate each one's chain independently — so you can
   *    wire multiple nodes into a loop and they all appear in the body.
   */
  function getLoopBodyLines(loopId: string, indentLevel: number): string[] {
    // 1. Explicit body handle edges (support multiple wires from "body")
    const bodyEdges = edges.filter((e) => e.source === loopId && e.sourceHandle === "body");
    if (bodyEdges.length > 0) {
      const result: string[] = [];
      const targets = bodyEdges
        .map((e) => nodeMap.get(e.target))
        .filter((n): n is Node => !!n)
        .sort((a, b) => a.position.y - b.position.y);
      for (const t of targets) result.push(...generateChain(t.id, indentLevel));
      return result;
    }

    // 2. Fall back: every directly-connected node below the loop node by Y
    const loopNode = nodeMap.get(loopId);
    if (!loopNode) return [];
    const connectedBelow = edges
      .filter((e) => e.source === loopId)
      .map((e) => nodeMap.get(e.target))
      .filter((n): n is Node => !!n && n.position.y > loopNode.position.y)
      .sort((a, b) => a.position.y - b.position.y);

    if (connectedBelow.length === 0) return [];
    // Generate each top-level body node independently so ALL of them are included
    const result: string[] = [];
    for (const bodyNode of connectedBelow) {
      result.push(...generateChain(bodyNode.id, indentLevel));
    }
    return result;
  }

  function generateChain(nodeId: string | null, indentLevel: number): string[] {
    if (!nodeId) return [];
    if (visited.has(nodeId)) return [];
    visited.add(nodeId);

    const node = nodeMap.get(nodeId);
    if (!node) return [];

    const d: any = node.data || {};
    const indent = "    ".repeat(indentLevel);
    const chunkLines: string[] = [];

    // Helper to get connected target of a specific handle ID (first match)
    const getTargetForHandle = (handleId: string) => {
      const edge = edges.find(
        (e) => e.source === nodeId && e.sourceHandle === handleId
      );
      return edge ? edge.target : null;
    };

    // Helper to get ALL connected targets for a handle, sorted by Y position
    const getAllTargetsForHandle = (handleId: string): string[] => {
      return edges
        .filter((e) => e.source === nodeId && e.sourceHandle === handleId)
        .map((e) => nodeMap.get(e.target))
        .filter((n): n is Node => !!n)
        .sort((a, b) => a.position.y - b.position.y)
        .map((n) => n.id);
    };

    // Helper to generate lines for multiple branch targets
    const getBranchLines = (handleId: string, indentLvl: number): string[] => {
      const targets = getAllTargetsForHandle(handleId);
      if (targets.length === 0) return [];
      const result: string[] = [];
      for (const tid of targets) result.push(...generateChain(tid, indentLvl));
      return result;
    };

    // Helper to get next sequential statement connected to standard bottom handle.
    // For loop nodes, skip edges used by getLoopBodyLines (body handle, or the
    // first below-node fallback) so the body isn't also emitted as a sequel.
    const getNextNodeId = () => {
      const isLoopNode = LOOP_TYPES.includes(node.type ?? "");
      const edge = edges.find((e) => {
        if (e.source !== nodeId) return false;
        const handle = e.sourceHandle ?? "";
        if (handle === "body" || handle === "true" || handle === "false") return false;
        // For loops using the Y-fallback body, skip the edge we used as body
        if (isLoopNode && !edges.some((b) => b.source === nodeId && b.sourceHandle === "body")) {
          const tgt = nodeMap.get(e.target);
          if (tgt && tgt.position.y > node.position.y) return false; // this is the body edge
        }
        return true;
      });
      return edge ? edge.target : null;
    };

    switch (node.type) {
      // ─── General ──────────────────────────────────────────────────────────
      case "print":
        chunkLines.push(`${indent}print(${d.text ?? "'Hello world'"})`);
        break;
      case "sleep":
        imports.add("import time");
        chunkLines.push(`${indent}time.sleep(${d.seconds ?? 1})`);
        break;
      case "variable":
        chunkLines.push(`${indent}${d.name ?? "x"} = ${d.value ?? 0}`);
        break;

      // ─── GPIO Pin / Controls ───────────────────────────────────────────────
      case "gpio_pin":
        imports.add("from machine import Pin");
        setupLines.push(`pin_${d.pin ?? 2} = Pin(${d.pin ?? 2}, Pin.${d.mode ?? "OUT"})`);
        break;
      case "pin_write":
        imports.add("from machine import Pin");
        chunkLines.push(`${indent}pin_${d.pin ?? 4}.value(${d.value ? 1 : 0})`);
        break;
      case "pin_read":
        imports.add("from machine import Pin");
        chunkLines.push(`${indent}${d.varName ?? "value"} = pin_${d.pin ?? 4}.value()`);
        break;
      case "pwm":
        imports.add("from machine import Pin, PWM");
        setupLines.push(`pwm_${d.pin ?? 2} = PWM(Pin(${d.pin ?? 2}), freq=${d.freq ?? 1000})`);
        chunkLines.push(`${indent}pwm_${d.pin ?? 2}.duty(${d.duty ?? 512})`);
        break;
      case "adc":
        imports.add("from machine import ADC, Pin");
        setupLines.push(`adc_${d.pin ?? 34} = ADC(Pin(${d.pin ?? 34}))`);
        chunkLines.push(`${indent}${d.varName ?? "value"} = adc_${d.pin ?? 34}.read_u16()`);
        break;
      case "push_button":
        imports.add("from machine import Pin");
        setupLines.push(`btn_${d.pin ?? 4} = Pin(${d.pin ?? 4}, Pin.IN)`);
        chunkLines.push(`${indent}${d.varName ?? "value"} = btn_${d.pin ?? 4}.value()`);
        break;
      case "buzzer_tone":
        imports.add("from machine import Pin, PWM");
        imports.add("import time");
        setupLines.push(`buzzer = PWM(Pin(${d.pin ?? 46}))`);
        chunkLines.push(`${indent}buzzer.freq(${Number(d.tone ?? 1) * 440})`);
        chunkLines.push(`${indent}buzzer.duty(512)`);
        break;
      case "neopixel_led":
        imports.add("from machine import Pin");
        imports.add("import neopixel");
        setupLines.push(`np = neopixel.NeoPixel(Pin(${d.pin ?? 48}), 1)`);
        {
          const c = d.color ?? "#ff0000";
          const r = parseInt(c.slice(1, 3), 16);
          const g = parseInt(c.slice(3, 5), 16);
          const b = parseInt(c.slice(5, 7), 16);
          const br = (d.brightness ?? 50) / 100;
          chunkLines.push(`${indent}np[0] = (${Math.round(r * br)}, ${Math.round(g * br)}, ${Math.round(b * br)})`);
          chunkLines.push(`${indent}np.write()`);
        }
        break;
      case "neopixel_rgb":
        imports.add("from machine import Pin");
        imports.add("import neopixel");
        setupLines.push(`np = neopixel.NeoPixel(Pin(${d.pin ?? 48}), 1)`);
        {
          const br = (d.brightness ?? 50) / 100;
          chunkLines.push(`${indent}np[0] = (${Math.round((d.red ?? 255) * br)}, ${Math.round((d.green ?? 0) * br)}, ${Math.round((d.blue ?? 0) * br)})`);
          chunkLines.push(`${indent}np.write()`);
        }
        break;

      case "neopixel_designer": {
        imports.add("from machine import Pin");
        imports.add("import neopixel, time");
        const npPin = d.pin ?? 48;
        const npCount = d.ledCount ?? 8;
        const npFps = d.fps ?? 10;
        const npFrames = d.frames as number[][][] | undefined;
        setupLines.push(`np = neopixel.NeoPixel(Pin(${npPin}), ${npCount})`);
        const clampRGB = (v: number) => Math.max(0, Math.min(255, Math.round(v)));
        if (npFrames && npFrames.length > 1) {
          const framesStr = npFrames
            .map(f => `    [${f.map((rgb: number[]) => `(${clampRGB(rgb[0])},${clampRGB(rgb[1])},${clampRGB(rgb[2])})`).join(",")}]`)
            .join(",\n");
          setupLines.push(`_np_frames = [\n${framesStr}\n]`);
          chunkLines.push(`${indent}for _f in _np_frames:`);
          chunkLines.push(`${indent}    for _i, _rgb in enumerate(_f): np[_i] = _rgb`);
          chunkLines.push(`${indent}    np.write()`);
          chunkLines.push(`${indent}    time.sleep_ms(${Math.round(1000 / npFps)})`);
        } else if (npFrames && npFrames.length === 1) {
          for (let i = 0; i < npFrames[0].length && i < npCount; i++) {
            const [r, g, b] = npFrames[0][i];
            chunkLines.push(`${indent}np[${i}] = (${clampRGB(r)},${clampRGB(g)},${clampRGB(b)})`);
          }
          chunkLines.push(`${indent}np.write()`);
        }
        break;
      }

      // ─── Loops ─────────────────────────────────────────────────────────────
      case "forever_loop":
        chunkLines.push(`${indent}while True:`);
        {
          const bodyLines = getLoopBodyLines(nodeId, indentLevel + 1);
          chunkLines.push(...(bodyLines.length > 0 ? bodyLines : [`${indent}    pass`]));
        }
        break;
      case "for_loop":
        chunkLines.push(`${indent}for ${d.variable ?? "i"} in range(${d.start ?? 0}, ${d.end ?? 10}, ${d.step ?? 1}):`);
        {
          const bodyLines = getLoopBodyLines(nodeId, indentLevel + 1);
          chunkLines.push(...(bodyLines.length > 0 ? bodyLines : [`${indent}    pass`]));
        }
        break;
      case "while_loop":
        chunkLines.push(`${indent}while ${d.condition ?? "True"}:`);
        {
          const bodyLines = getLoopBodyLines(nodeId, indentLevel + 1);
          chunkLines.push(...(bodyLines.length > 0 ? bodyLines : [`${indent}    pass`]));
        }
        break;
      case "repeat":
        chunkLines.push(`${indent}for _ in range(${d.times ?? 1}):`);
        {
          const bodyLines = getLoopBodyLines(nodeId, indentLevel + 1);
          chunkLines.push(...(bodyLines.length > 0 ? bodyLines : [`${indent}    pass`]));
        }
        break;
      case "break":
        chunkLines.push(`${indent}break`);
        break;

      // ─── Conditional ───────────────────────────────────────────────────────
      case "if_else":
        chunkLines.push(`${indent}if ${d.left ?? ""} ${d.op ?? "=="} ${d.right ?? 0}:`);
        {
          const trueLines = getBranchLines("true", indentLevel + 1);
          chunkLines.push(...(trueLines.length > 0 ? trueLines : [`${indent}    pass`]));
        }
        chunkLines.push(`${indent}else:`);
        {
          const falseLines = getBranchLines("false", indentLevel + 1);
          chunkLines.push(...(falseLines.length > 0 ? falseLines : [`${indent}    pass`]));
        }
        break;

      // ─── IOT ───────────────────────────────────────────────────────────────
      case "wifi_connect":
        imports.add("import network");
        imports.add("import time");
        chunkLines.push(`${indent}wlan = network.WLAN(network.STA_IF)`);
        chunkLines.push(`${indent}wlan.active(True)`);
        chunkLines.push(`${indent}wlan.connect('${d.ssid ?? "MyWiFi"}', '${d.password ?? "password"}')`);
        chunkLines.push(`${indent}while not wlan.isconnected():`);
        chunkLines.push(`${indent}    time.sleep(0.5)`);
        chunkLines.push(`${indent}print('WiFi connected:', wlan.ifconfig()[0])`);
        break;
      case "http_get":
        imports.add("import urequests");
        chunkLines.push(`${indent}${d.varName ?? "response"} = urequests.get('${d.url ?? "http://example.com"}').text`);
        break;
      case "esp_now_sender":
        imports.add("import espnow");
        imports.add("import network");
        chunkLines.push(`${indent}# ESP NOW Send to ${d.mac ?? "FF:FF:FF:FF:FF:FF"}`);
        chunkLines.push(`${indent}en = espnow.ESPNow()`);
        chunkLines.push(`${indent}en.active(True)`);
        chunkLines.push(`${indent}en.add_peer(b'${d.mac?.replace(/:/g, "\\x") ?? "\\xff\\xff\\xff\\xff\\xff\\xff"}')`);
        chunkLines.push(`${indent}en.send(b'${d.sendData ?? "hello"}')`);
        break;
      case "time_online":
        imports.add("import ntptime");
        imports.add("import time");
        chunkLines.push(`${indent}ntptime.settime()`);
        chunkLines.push(`${indent}${d.varName ?? "time_now"} = time.localtime()`);
        break;

      // ─── Sensor ────────────────────────────────────────────────────────────
      case "ultrasonic":
        imports.add("from machine import Pin");
        imports.add("import time");
        chunkLines.push(`${indent}# Ultrasonic - Trig:${d.trigPin ?? 1} Echo:${d.echoPin ?? 5}`);
        chunkLines.push(`${indent}trig = Pin(${d.trigPin ?? 1}, Pin.OUT)`);
        chunkLines.push(`${indent}echo = Pin(${d.echoPin ?? 5}, Pin.IN)`);
        chunkLines.push(`${indent}trig.value(1); time.sleep_us(10); trig.value(0)`);
        chunkLines.push(`${indent}${d.varName ?? "distance"} = echo.value()`);
        break;
      case "touch_sensor":
        imports.add("from machine import TouchPad, Pin");
        chunkLines.push(`${indent}${d.varName ?? "touch_value"} = TouchPad(Pin(${d.pin ?? 4})).read()`);
        break;
      case "soil_moisture":
        imports.add("from machine import ADC, Pin");
        setupLines.push(`soil_moisture_${d.pin ?? 4} = ADC(Pin(${d.pin ?? 4}))`);
        chunkLines.push(`${indent}${d.varName ?? "value"} = soil_moisture_${d.pin ?? 4}.read_u16()`);
        break;
      case "ir_receiver":
        chunkLines.push(`${indent}# IR Receiver on pin ${d.pin ?? 5}`);
        chunkLines.push(`${indent}${d.varName ?? "ir_cmd"} = 0  # Read from IR receiver`);
        break;
      case "ir_sensor":
        imports.add("from machine import Pin");
        chunkLines.push(`${indent}${d.varName ?? "ir_value"} = Pin(${d.pin ?? 4}, Pin.IN).value()`);
        break;

      case "four_channel_touch":
        imports.add("from machine import TouchPad, Pin");
        chunkLines.push(`${indent}# Four channel touch sensor: ${d.t1 ?? "touch1"}, ${d.t2 ?? "touch2"}, ${d.t3 ?? "touch3"}, ${d.t4 ?? "touch4"}`);
        chunkLines.push(`${indent}${d.t1 ?? "touch1"} = TouchPad(Pin(${d.pin1 ?? 4})).read()`);
        chunkLines.push(`${indent}${d.t2 ?? "touch2"} = TouchPad(Pin(${d.pin2 ?? 5})).read()`);
        chunkLines.push(`${indent}${d.t3 ?? "touch3"} = TouchPad(Pin(${d.pin3 ?? 6})).read()`);
        chunkLines.push(`${indent}${d.t4 ?? "touch4"} = TouchPad(Pin(${d.pin4 ?? 7})).read()`);
        break;

      // ─── Display ───────────────────────────────────────────────────────────
      case "oled_display": {
        // d.driver: false = SH1106 (default), true = SSD1306
        const useSSD = d.driver === true;
        const dLib   = useSSD ? "ssd1306" : "sh1106";
        const dClass = useSSD ? "SSD1306_I2C" : "SH1106_I2C";
        const [oledW, oledH] = d.resolution === "128x32" ? [128, 32] : [128, 64];

        imports.add("from machine import SoftI2C, Pin");
        imports.add(`import ${dLib}`);
        setupLines.push(`i2c = SoftI2C(scl=Pin(${d.sck ?? 36}), sda=Pin(${d.sda ?? 35}))`);
        setupLines.push(`oled = ${dLib}.${dClass}(${oledW}, ${oledH}, i2c)`);

        // Always clear before drawing
        chunkLines.push(`${indent}oled.fill(0)`);

        // Static pixel art (drawn in the node's OLED designer)
        const staticPixels = d.staticPixels as boolean[][] | undefined;
        if (staticPixels && staticPixels.some(row => row.some(v => v))) {
          imports.add("import framebuf");
          const hexStr = bytesToPyHex(oledPixelsToMonoHLSB(staticPixels, oledW, oledH));
          chunkLines.push(`${indent}_fb = framebuf.FrameBuffer(bytearray(b'${hexStr}'), ${oledW}, ${oledH}, framebuf.MONO_HLSB)`);
          chunkLines.push(`${indent}oled.blit(_fb, 0, 0)`);
        }

        // Animation frames
        const animFrames = d.animFrames as boolean[][][] | undefined;
        if (animFrames && animFrames.length > 1) {
          imports.add("import framebuf");
          imports.add("import time");
          const framesStr = animFrames.map(f => {
            const hex = bytesToPyHex(oledPixelsToMonoHLSB(f, oledW, oledH));
            return `b'${hex}'`;
          }).join(", ");
          const fps = typeof d.fps === "number" ? d.fps : 10;
          const delayMs = Math.round(1000 / fps);
          setupLines.push(`_oled_frames = [${framesStr}]`);
          chunkLines.push(`${indent}for _fd in _oled_frames:`);
          chunkLines.push(`${indent}    _fb = framebuf.FrameBuffer(bytearray(_fd), ${oledW}, ${oledH}, framebuf.MONO_HLSB)`);
          chunkLines.push(`${indent}    oled.fill(0); oled.blit(_fb, 0, 0); oled.show()`);
          chunkLines.push(`${indent}    time.sleep_ms(${delayMs})`);
        } else {
          // Text lines
          const line1 = typeof d.line1 === "string" ? d.line1 : "";
          const line2 = typeof d.line2 === "string" ? d.line2 : "";
          if (line1) chunkLines.push(`${indent}oled.text(${JSON.stringify(line1)}, 0, 0)`);
          if (line2) chunkLines.push(`${indent}oled.text(${JSON.stringify(line2)}, 0, 12)`);
          chunkLines.push(`${indent}oled.show()`);
        }
        break;
      }
      case "seven_seg":
        imports.add("import tm1637");
        imports.add("from machine import Pin");
        setupLines.push(`tm = tm1637.TM1637(clk=Pin(${d.clk ?? 17}), dio=Pin(${d.dio ?? 18}))`);
        chunkLines.push(`${indent}tm.number(${d.number ?? 1234})`);
        break;
      case "servo_motor":
        imports.add("from machine import Pin, PWM");
        setupLines.push(`servos = {}
def rotate_servo(pin_num, angle):
    global servos
    if pin_num not in servos:
        pwm = PWM(Pin(pin_num, Pin.OUT), freq=50)
        servos[pin_num] = pwm
    pwm = servos[pin_num]
    angle = max(0, min(180, int(angle)))
    us = 600 + (angle / 180) * 1800
    pwm.duty_u16(int(us / 20000 * 65535))`);
        {
          const angleVal = d.angle ?? 90;
          chunkLines.push(`${indent}rotate_servo(${d.pin ?? 21}, ${angleVal})`);
        }
        break;
      case "servo_motor_advance":
        imports.add("from machine import Pin, PWM");
        imports.add("import time");
        setupLines.push(`servos = {}
def rotate_servo(pin_num, angle):
    global servos
    if pin_num not in servos:
        pwm = PWM(Pin(pin_num, Pin.OUT), freq=50)
        servos[pin_num] = pwm
    pwm = servos[pin_num]
    angle = max(0, min(180, int(angle)))
    us = 600 + (angle / 180) * 1800
    pwm.duty_u16(int(us / 20000 * 65535))`);
        chunkLines.push(`${indent}# Sweep from ${d.startAngle ?? 0} to ${d.endAngle ?? 90} at speed ${d.speed ?? 50}`);
        chunkLines.push(`${indent}for angle in range(${d.startAngle ?? 0}, ${d.endAngle ?? 90}, ${Math.max(1, Math.round((d.speed ?? 50) / 10))}):`);
        chunkLines.push(`${indent}    rotate_servo(${d.pin ?? 21}, angle)`);
        chunkLines.push(`${indent}    time.sleep_ms(${Math.max(10, 100 - (d.speed ?? 50))})`);
        break;
      case "l298n_motor":
        imports.add("from machine import Pin");
        setupLines.push(`motor_in1 = Pin(${d.in1 ?? 13}, Pin.OUT)`);
        setupLines.push(`motor_in2 = Pin(${d.in2 ?? 21}, Pin.OUT)`);
        setupLines.push(`motor_in3 = Pin(${d.in3 ?? 14}, Pin.OUT)`);
        setupLines.push(`motor_in4 = Pin(${d.in4 ?? 12}, Pin.OUT)`);
        {
          const dir = d.direction ?? "Forward";
          if (dir === "Forward") {
            chunkLines.push(`${indent}motor_in1.value(1); motor_in2.value(0); motor_in3.value(1); motor_in4.value(0)`);
          } else if (dir === "Backward") {
            chunkLines.push(`${indent}motor_in1.value(0); motor_in2.value(1); motor_in3.value(0); motor_in4.value(1)`);
          } else if (dir === "Left") {
            chunkLines.push(`${indent}motor_in1.value(0); motor_in2.value(1); motor_in3.value(1); motor_in4.value(0)`);
          } else if (dir === "Right") {
            chunkLines.push(`${indent}motor_in1.value(1); motor_in2.value(0); motor_in3.value(0); motor_in4.value(1)`);
          } else {
            chunkLines.push(`${indent}motor_in1.value(0); motor_in2.value(0); motor_in3.value(0); motor_in4.value(0)`);
          }
        }
        break;

      // ─── New Sensor Nodes ──────────────────────────────────────────────────
      case "analog_sensor":
        imports.add("from machine import ADC, Pin");
        setupLines.push(`adc_${d.pin ?? 34} = ADC(Pin(${d.pin ?? 34}))`);
        chunkLines.push(`${indent}${d.varName ?? "analog_val"} = adc_${d.pin ?? 34}.read_u16() >> 4  # 12-bit`);
        break;
      case "button_digital_input":
        imports.add("from machine import Pin");
        {
          const pullMode = d.pullup ? "Pin.PULL_UP" : "Pin.PULL_DOWN";
          setupLines.push(`btn_${d.pin ?? 0} = Pin(${d.pin ?? 0}, Pin.IN, ${pullMode})`);
          chunkLines.push(`${indent}${d.varName ?? "btn"} = btn_${d.pin ?? 0}.value()`);
        }
        break;

      // ─── New Display Nodes ─────────────────────────────────────────────────
      case "lcd_16x2":
        imports.add("from machine import I2C, Pin");
        imports.add("import lcd_api, i2c_lcd");
        setupLines.push(`i2c_lcd_bus = I2C(0, scl=Pin(${d.scl ?? 22}), sda=Pin(${d.sda ?? 21}), freq=400000)`);
        setupLines.push(`lcd = i2c_lcd.I2cLcd(i2c_lcd_bus, ${d.address ?? "0x27"}, 2, 16)`);
        chunkLines.push(`${indent}lcd.clear()`);
        chunkLines.push(`${indent}lcd.putstr(${d.line1 ?? "'Hello'"})`);
        chunkLines.push(`${indent}lcd.move_to(0, 1)`);
        chunkLines.push(`${indent}lcd.putstr(${d.line2 ?? "'World'"})`);
        break;

      // ─── New GPIO/Output Nodes ─────────────────────────────────────────────
      case "rgb_led_matrix":
        imports.add("import neopixel");
        imports.add("from machine import Pin");
        setupLines.push(`rgb_matrix = neopixel.NeoPixel(Pin(${d.pin ?? 48}), ${d.ledCount ?? 16})`);
        chunkLines.push(`${indent}# Pattern: ${d.pattern ?? "Chase"} on ${d.ledCount ?? 16} LEDs`);
        chunkLines.push(`${indent}for i in range(len(rgb_matrix)):`);
        chunkLines.push(`${indent}    rgb_matrix[i] = (${Math.round((d.brightness ?? 128))}, 0, 0)`);
        chunkLines.push(`${indent}rgb_matrix.write()`);
        break;
      case "pwm_output":
        imports.add("from machine import Pin, PWM");
        setupLines.push(`pwm_out_${d.pin ?? 2} = PWM(Pin(${d.pin ?? 2}), freq=${d.freq ?? 1000})`);
        chunkLines.push(`${indent}pwm_out_${d.pin ?? 2}.duty(${Math.round(((d.duty ?? 50) / 100) * 1023)})`);
        break;

      // ─── New Motor Nodes ───────────────────────────────────────────────────
      case "dc_motor_single": {
        // DRV8833: one PWM pin + one DIR pin per motor channel
        // Board MOTOR_PORTS: L1(pwm=15,dir=16), L2(pwm=37,dir=38), R1(pwm=45,dir=46), R2(pwm=17,dir=18)
        imports.add("from machine import Pin, PWM");
        const motorPortMap: Record<string, { pwm: number; dir: number }> = {
          L1: { pwm: 15, dir: 16 }, L2: { pwm: 37, dir: 38 },
          R1: { pwm: 45, dir: 46 }, R2: { pwm: 17, dir: 18 },
        };
        const mKey = (d.motorPort as string) ?? "L1";
        const mp = motorPortMap[mKey] ?? motorPortMap["L1"];
        setupLines.push(`drv_pwm_${mKey} = PWM(Pin(${mp.pwm}, Pin.OUT), freq=40000)`);
        setupLines.push(`drv_dir_${mKey} = Pin(${mp.dir}, Pin.OUT)`);
        {
          const dir = d.direction ?? "Forward";
          const speed = d.speed ?? 50;
          const duty = Math.round((speed / 100) * 65535);
          const rduty = 65535 - duty;
          if (dir === "Forward") {
            chunkLines.push(`${indent}drv_dir_${mKey}.value(0); drv_pwm_${mKey}.duty_u16(${duty})`);
          } else if (dir === "Reverse") {
            chunkLines.push(`${indent}drv_dir_${mKey}.value(1); drv_pwm_${mKey}.duty_u16(${rduty})`);
          } else if (dir === "Brake") {
            chunkLines.push(`${indent}drv_dir_${mKey}.value(0); drv_pwm_${mKey}.duty_u16(0)  # Brake`);
          } else {
            chunkLines.push(`${indent}drv_dir_${mKey}.value(0); drv_pwm_${mKey}.duty_u16(0)  # Coast`);
          }
        }
        break;
      }

      // ─── New Motor / Servo Nodes ───────────────────────────────────────────
      case "servo_controller": {
        imports.add("from machine import Pin, PWM");
        const scPin = d.pin ?? 21;
        const pulseMin = d.pulseMin ?? 600;
        const pulseMax = d.pulseMax ?? 2400;
        setupLines.push(`sc_pwm_${scPin} = PWM(Pin(${scPin}, Pin.OUT), freq=50)`);
        if (d.mode === "sweep") {
          imports.add("import time");
          chunkLines.push(`${indent}for _a in range(${d.sweepMin ?? 0}, ${d.sweepMax ?? 180}, 1):`);
          chunkLines.push(`${indent}    _us = ${pulseMin} + (_a / 180) * (${pulseMax} - ${pulseMin})`);
          chunkLines.push(`${indent}    sc_pwm_${scPin}.duty_u16(int(_us / 20000 * 65535))`);
          chunkLines.push(`${indent}    time.sleep_ms(${Math.round((d.sweepPeriod ?? 1000) / 180)})`);
        } else {
          const us = pulseMin + ((d.angle ?? 90) / 180) * (pulseMax - pulseMin);
          chunkLines.push(`${indent}sc_pwm_${scPin}.duty_u16(${Math.round((us / 20000) * 65535)})  # ${d.angle ?? 90}°`);
        }
        break;
      }
      case "multi_motor_controller": {
        // DRV8833 dual H-bridge — matches board wiring (same as reference hardware)
        imports.add("from machine import Pin, PWM");
        // Board motor ports: L1(pwm=15,dir=16), L2(pwm=37,dir=38), R1(pwm=45,dir=46), R2(pwm=17,dir=18)
        setupLines.push(`# DRV8833 motor driver setup
_motor_ports = {
    'L1': (PWM(Pin(15, Pin.OUT), freq=40000), Pin(16, Pin.OUT)),
    'L2': (PWM(Pin(37, Pin.OUT), freq=40000), Pin(38, Pin.OUT)),
    'R1': (PWM(Pin(45, Pin.OUT), freq=40000), Pin(46, Pin.OUT)),
    'R2': (PWM(Pin(17, Pin.OUT), freq=40000), Pin(18, Pin.OUT)),
}
def _drv_set(port, speed, forward=True):
    pwm, dir_pin = _motor_ports[port]
    dir_pin.value(0 if forward else 1)
    duty = int(abs(speed) / 100 * 65535)
    pwm.duty_u16(duty if forward else 65535 - duty)`);
        if (d.syncMode) {
          const spd = d.l1speed ?? d.m1speed ?? 50;
          const fwd = (d.l1dir ?? d.m1dir ?? "Forward") === "Forward";
          chunkLines.push(`${indent}# All motors synced — speed ${spd}% ${fwd ? "forward" : "reverse"}`);
          for (const port of ["L1", "L2", "R1", "R2"]) {
            chunkLines.push(`${indent}_drv_set('${port}', ${spd}, ${fwd})`);
          }
        } else if (d.pairMode) {
          const lSpd = d.leftSpeed ?? 50; const lFwd = (d.leftDir ?? "Forward") === "Forward";
          const rSpd = d.rightSpeed ?? 50; const rFwd = (d.rightDir ?? "Forward") === "Forward";
          chunkLines.push(`${indent}# Left motors: ${lSpd}% ${lFwd ? "fwd" : "rev"}  Right: ${rSpd}% ${rFwd ? "fwd" : "rev"}`);
          chunkLines.push(`${indent}_drv_set('L1', ${lSpd}, ${lFwd}); _drv_set('L2', ${lSpd}, ${lFwd})`);
          chunkLines.push(`${indent}_drv_set('R1', ${rSpd}, ${rFwd}); _drv_set('R2', ${rSpd}, ${rFwd})`);
        } else {
          const ports = ["L1", "L2", "R1", "R2"] as const;
          const speeds = [d.l1speed ?? 50, d.l2speed ?? 50, d.r1speed ?? 50, d.r2speed ?? 50];
          const dirs   = [d.l1dir ?? "Forward", d.l2dir ?? "Forward", d.r1dir ?? "Forward", d.r2dir ?? "Forward"];
          for (let i = 0; i < 4; i++) {
            chunkLines.push(`${indent}_drv_set('${ports[i]}', ${speeds[i]}, ${dirs[i] === "Forward"})`);
          }
        }
        break;
      }
      case "multi_servo_sequencer": {
        imports.add("from machine import Pin, PWM");
        imports.add("import time");
        // Board servo ports: S1=21, S2=47, S3=39, S4=40
        const mssP1 = d.servo1pin ?? d.s1pin ?? 21;
        const mssP2 = d.servo2pin ?? d.s2pin ?? 47;
        const mssP3 = d.servo3pin ?? d.s3pin ?? 39;
        setupLines.push(`mss_servos = [PWM(Pin(${mssP1}, Pin.OUT), freq=50), PWM(Pin(${mssP2}, Pin.OUT), freq=50), PWM(Pin(${mssP3}, Pin.OUT), freq=50)]`);
        setupLines.push(`def _mss_angle(pwm, deg):
    us = 600 + (max(0, min(180, deg)) / 180) * 1800
    pwm.duty_u16(int(us / 20000 * 65535))`);
        chunkLines.push(`${indent}# Multi-Servo Sequencer — keyframe delay: ${d.keyframeDelay ?? 500}ms`);
        if (d.keyframes && Array.isArray(d.keyframes)) {
          for (const kf of d.keyframes) {
            for (let si = 0; si < Math.min(3, kf.angles?.length ?? 0); si++) {
              chunkLines.push(`${indent}_mss_angle(mss_servos[${si}], ${kf.angles[si]})`);
            }
            chunkLines.push(`${indent}time.sleep_ms(${d.keyframeDelay ?? 500})`);
          }
        } else {
          chunkLines.push(`${indent}for _s in mss_servos: _mss_angle(_s, 90)  # center all`);
          chunkLines.push(`${indent}time.sleep_ms(${d.keyframeDelay ?? 500})`);
        }
        break;
      }

      // ─── Comms Nodes ───────────────────────────────────────────────────────
      case "ble_mode":
        imports.add("import bluetooth");
        imports.add("from ble_simple_peripheral import BLESimplePeripheral");
        setupLines.push(`ble = bluetooth.BLE()`);
        setupLines.push(`ble_sp = BLESimplePeripheral(ble, name="${d.deviceName ?? "ESP32-BLE"}")`);
        chunkLines.push(`${indent}${d.varName ?? "ble_cmd"} = None`);
        chunkLines.push(`${indent}if ble_sp.is_connected():`);
        chunkLines.push(`${indent}    ${d.varName ?? "ble_cmd"} = ble_sp.read()`);
        break;
      case "wifi_node":
        imports.add("import network");
        imports.add("import time");
        {
          const wMode = d.mode === "ap" ? "AP" : "STA";
          setupLines.push(`wlan = network.WLAN(network.${wMode}_IF)`);
          setupLines.push(`wlan.active(True)`);
          if (d.mode === "ap") {
            setupLines.push(`wlan.config(essid="${d.ssid ?? "ESP32-AP"}", password="${d.password ?? "password123"}")`);
          } else {
            setupLines.push(`wlan.connect("${d.ssid ?? "MyNetwork"}", "${d.password ?? "password123"}")`);
            setupLines.push(`while not wlan.isconnected(): time.sleep_ms(100)`);
          }
        }
        chunkLines.push(`${indent}${d.varName ?? "ip"} = wlan.ifconfig()[0]`);
        break;

      case "esp_now_receiver":
        imports.add("import espnow");
        imports.add("import network");
        chunkLines.push(`${indent}# ESP NOW Receive from peer`);
        chunkLines.push(`${indent}en = espnow.ESPNow()`);
        chunkLines.push(`${indent}en.active(True)`);
        chunkLines.push(`${indent}${d.varName ?? "espnow_msg"} = en.recv(1024)`);
        break;

      case "mqtt_node":
        imports.add("import network");
        imports.add("from umqtt.simple import MQTTClient");
        chunkLines.push(`${indent}# MQTT node for topic ${d.topic ?? "sensors/data"}`);
        chunkLines.push(`${indent}mqtt_client = MQTTClient("${d.clientId ?? "kakoon-client"}", "${d.broker ?? "broker.hivemq.com"}")`);
        chunkLines.push(`${indent}mqtt_client.connect()`);
        chunkLines.push(`${indent}mqtt_client.publish(b"${d.topic ?? "sensors/data"}", b"${d.payload ?? "hello"}")`);
        break;

      case "http_client":
        imports.add("import urequests");
        chunkLines.push(`${indent}${d.varName ?? "response"} = urequests.get("${d.url ?? "http://example.com"}").text`);
        break;

      case "serial_monitor":
        chunkLines.push(`${indent}print(${d.value ?? "'Serial monitor output'"})`);
        break;

      case "timer_interval":
        imports.add("import time");
        chunkLines.push(`${indent}_last_tick = time.ticks_ms()`);
        chunkLines.push(`${indent}if time.ticks_diff(time.ticks_ms(), _last_tick) >= ${d.interval ?? 1000}:`);
        chunkLines.push(`${indent}    _last_tick = time.ticks_ms()`);
        chunkLines.push(`${indent}    ${d.varName ?? "timer_fired"} = True`);
        break;

      case "variable_state":
        chunkLines.push(`${indent}# Variable state tracker: ${d.name ?? "state"}`);
        chunkLines.push(`${indent}${d.varName ?? "state"} = ${d.value ?? "None"}`);
        break;

      case "math_transform":
        chunkLines.push(`${indent}${d.varName ?? "result"} = ${d.expression ?? "0"}`);
        break;

      case "deep_sleep":
        imports.add("from machine import deepsleep");
        chunkLines.push(`${indent}deepsleep(${d.durationMs ?? 1000})`);
        break;

      case "ota_update":
        chunkLines.push(`${indent}# OTA update placeholder: ${d.url ?? "configure an update URL"}`);
        break;

      case "sd_card":
        imports.add("from machine import SPI, Pin");
        imports.add("import sdcard");
        chunkLines.push(`${indent}# SD card mount on CS pin ${d.csPin ?? 5}`);
        chunkLines.push(`${indent}spi = SPI(1, sck=Pin(${d.sck ?? 18}), mosi=Pin(${d.mosi ?? 23}), miso=Pin(${d.miso ?? 19}))`);
        chunkLines.push(`${indent}sd = sdcard.SDCard(spi, Pin(${d.csPin ?? 5}))`);
        break;

      case "max7219":
        imports.add("from machine import Pin, SPI");
        imports.add("import max7219");
        chunkLines.push(`${indent}# MAX7219 matrix: ${d.width ?? 8}x${d.height ?? 8}`);
        chunkLines.push(`${indent}spi = SPI(1, baudrate=10000000, polarity=0, phase=0)`);
        chunkLines.push(`${indent}display = max7219.Matrix8x8(spi, Pin(${d.csPin ?? 5}), ${d.width ?? 1}, ${d.height ?? 1})`);
        break;

      case "play_animation":
        chunkLines.push(`${indent}# Play animation: ${d.animationName ?? "default"}`);
        chunkLines.push(`${indent}# Animation frames should be supplied by the runtime or library layer.`);
        break;

      case "show_image":
        chunkLines.push(`${indent}# Show image: ${d.imageName ?? "image"}`);
        chunkLines.push(`${indent}# Image rendering is handled by the display library at runtime.`);
        break;

      // ─── Tool Nodes ────────────────────────────────────────────────────────
      case "servo_calibration":
        chunkLines.push(`${indent}# Servo Calibration — compile-time utility only (no runtime code)`);
        break;
      case "i2c_scanner":
        imports.add("from machine import I2C, Pin");
        setupLines.push(`i2c_scan_bus = I2C(0, scl=Pin(${d.scl ?? 22}), sda=Pin(${d.sda ?? 21}))`);
        chunkLines.push(`${indent}i2c_devices = i2c_scan_bus.scan()`);
        chunkLines.push(`${indent}print("I2C devices found:", [hex(x) for x in i2c_devices])`);
        break;

      // ─── Math ──────────────────────────────────────────────────────────────
      case "map_range":
        setupLines.push(`def map_range(x, in_min, in_max, out_min, out_max):
    if in_max == in_min:
        return out_min
    return int((x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min)`);
        chunkLines.push(`${indent}${d.varName ?? "mapped_value"} = map_range(${d.value ?? "value"}, ${d.fromMin ?? 0}, ${d.fromMax ?? 4095}, ${d.toMin ?? 0}, ${d.toMax ?? 180})`);
        break;
      case "random_number":
        imports.add("import random");
        chunkLines.push(`${indent}${d.varName ?? "rand_val"} = random.randint(${d.from ?? 0}, ${d.to ?? 100})`);
        break;

      default:
        chunkLines.push(`${indent}# Unknown node type: ${node.type}`);
    }

    // Follow the sequential bottom handle path
    const nextId = getNextNodeId();
    if (nextId) {
      const nextLines = generateChain(nextId, indentLevel);
      return chunkLines.concat(nextLines);
    }
    return chunkLines;
  }

  // Walk all root nodes in sorted order
  const codeLines: string[] = [];
  for (const root of sortedRoots) {
    const chainLines = generateChain(root.id, 0);
    if (chainLines.length > 0) {
      codeLines.push(...chainLines);
      codeLines.push(""); // add spacer between independent loops/routines
    }
  }

  // Assemble the Python code
  if (imports.size > 0) {
    lines.push(...Array.from(imports));
    lines.push("");
  }
  if (setupLines.length > 0) {
    // Unique the setup lines
    const uniqueSetups = Array.from(new Set(setupLines));
    lines.push(...uniqueSetups);
    lines.push("");
  }
  lines.push(...codeLines);

  // Trim trailing spacer lines
  return lines.join("\n").replace(/\n+$/, "\n");
}
