/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Node, Edge } from "@xyflow/react";

/**
 * Robust Graph Traversal Code Generator for Kakoon CodeLab.
 * Walks the connected flow starting from root nodes (unconnected/entry points),
 * recursing into loop body and conditional branches, and following sequence lines.
 */
export function generatePythonFromFlow(nodes: Node[], edges: Edge[]): string {
  if (nodes.length === 0) return "# Add nodes to generate code\n";

  const nodeMap = new Map<string, Node>();
  for (const n of nodes) nodeMap.set(n.id, n);

  // Use edges exactly as drawn — no flipping/normalization.
  // Users connect nodes in execution order; the direction is correct by design.

  // Root nodes = nodes that have no incoming flow edges
  // (ignore incoming "true"/"false"/"body" handle edges — those are branch entries, not sequential flow)
  const hasIncomingFlow = new Set<string>();
  for (const e of edges) {
    // An edge pointing INTO a node counts as "has incoming flow" only if it's
    // a plain sequential edge (not a body/true/false branch handle from a loop/conditional)
    const srcHandle = e.sourceHandle ?? "";
    if (srcHandle !== "body" && srcHandle !== "true" && srcHandle !== "false") {
      hasIncomingFlow.add(e.target);
    }
  }
  const rootNodes = nodes.filter((n) => !hasIncomingFlow.has(n.id));
  const sortedRoots = [...rootNodes].sort((a, b) => a.position.y - b.position.y);

  const lines: string[] = ["# Generated by Kakoon CodeLab Node Editor", ""];

  // Collect imports and setups
  const imports = new Set<string>();
  const setupLines: string[] = [];

  const visited = new Set<string>();

  // Loop types that use getLoopBodyLines for their body
  const LOOP_TYPES = ["forever_loop", "for_loop", "while_loop", "repeat"];

  /**
   * Returns the lines for the body of a loop node.
   *
   * Strategy (in order):
   * 1. If a "body" handle edge exists, follow that chain — explicit wiring wins.
   * 2. Otherwise, collect every directly-connected node that has a Y position
   *    greater than the loop node (i.e. drawn below it), sort them by Y, and
   *    use the topmost one as the body entry — so just connecting nodes below
   *    the loop with any edge "just works" without a special body handle.
   */
  function getLoopBodyLines(loopId: string, indentLevel: number): string[] {
    // 1. Explicit body handle
    const bodyEdge = edges.find((e) => e.source === loopId && e.sourceHandle === "body");
    if (bodyEdge) return generateChain(bodyEdge.target, indentLevel);

    // 2. Fall back: any directly connected node below the loop node by Y
    const loopNode = nodeMap.get(loopId);
    if (!loopNode) return [];
    const connectedBelow = edges
      .filter((e) => e.source === loopId && e.sourceHandle !== "body")
      .map((e) => nodeMap.get(e.target))
      .filter((n): n is Node => !!n && n.position.y > loopNode.position.y)
      .sort((a, b) => a.position.y - b.position.y);

    if (connectedBelow.length === 0) return [];
    return generateChain(connectedBelow[0].id, indentLevel);
  }

  function generateChain(nodeId: string | null, indentLevel: number): string[] {
    if (!nodeId) return [];
    if (visited.has(nodeId)) return [];
    visited.add(nodeId);

    const node = nodeMap.get(nodeId);
    if (!node) return [];

    const d: any = node.data || {};
    const indent = "    ".repeat(indentLevel);
    const chunkLines: string[] = [];

    // Helper to get connected target of a specific handle ID
    const getTargetForHandle = (handleId: string) => {
      const edge = edges.find(
        (e) => e.source === nodeId && e.sourceHandle === handleId
      );
      return edge ? edge.target : null;
    };

    // Helper to get next sequential statement connected to standard bottom handle.
    // For loop nodes, skip edges used by getLoopBodyLines (body handle, or the
    // first below-node fallback) so the body isn't also emitted as a sequel.
    const getNextNodeId = () => {
      const isLoopNode = LOOP_TYPES.includes(node.type ?? "");
      const edge = edges.find((e) => {
        if (e.source !== nodeId) return false;
        const handle = e.sourceHandle ?? "";
        if (handle === "body" || handle === "true" || handle === "false") return false;
        // For loops using the Y-fallback body, skip the edge we used as body
        if (isLoopNode && !edges.some((b) => b.source === nodeId && b.sourceHandle === "body")) {
          const tgt = nodeMap.get(e.target);
          if (tgt && tgt.position.y > node.position.y) return false; // this is the body edge
        }
        return true;
      });
      return edge ? edge.target : null;
    };

    switch (node.type) {
      // ─── General ──────────────────────────────────────────────────────────
      case "print":
        chunkLines.push(`${indent}print(${d.text ?? "'Hello world'"})`);
        break;
      case "sleep":
        imports.add("import time");
        chunkLines.push(`${indent}time.sleep(${d.seconds ?? 1})`);
        break;
      case "variable":
        chunkLines.push(`${indent}${d.name ?? "x"} = ${d.value ?? 0}`);
        break;

      // ─── GPIO Pin / Controls ───────────────────────────────────────────────
      case "gpio_pin":
        imports.add("from machine import Pin");
        setupLines.push(`pin_${d.pin ?? 2} = Pin(${d.pin ?? 2}, Pin.${d.mode ?? "OUT"})`);
        break;
      case "pin_write":
        imports.add("from machine import Pin");
        chunkLines.push(`${indent}pin_${d.pin ?? 4}.value(${d.value ? 1 : 0})`);
        break;
      case "pin_read":
        imports.add("from machine import Pin");
        chunkLines.push(`${indent}${d.varName ?? "value"} = pin_${d.pin ?? 4}.value()`);
        break;
      case "pwm":
        imports.add("from machine import Pin, PWM");
        setupLines.push(`pwm_${d.pin ?? 2} = PWM(Pin(${d.pin ?? 2}), freq=${d.freq ?? 1000})`);
        chunkLines.push(`${indent}pwm_${d.pin ?? 2}.duty(${d.duty ?? 512})`);
        break;
      case "adc":
        imports.add("from machine import ADC, Pin");
        setupLines.push(`adc_${d.pin ?? 34} = ADC(Pin(${d.pin ?? 34}))`);
        chunkLines.push(`${indent}${d.varName ?? "value"} = adc_${d.pin ?? 34}.read_u16()`);
        break;
      case "push_button":
        imports.add("from machine import Pin");
        setupLines.push(`btn_${d.pin ?? 4} = Pin(${d.pin ?? 4}, Pin.IN)`);
        chunkLines.push(`${indent}${d.varName ?? "value"} = btn_${d.pin ?? 4}.value()`);
        break;
      case "buzzer_tone":
        imports.add("from machine import Pin, PWM");
        imports.add("import time");
        setupLines.push(`buzzer = PWM(Pin(${d.pin ?? 46}))`);
        chunkLines.push(`${indent}buzzer.freq(${Number(d.tone ?? 1) * 440})`);
        chunkLines.push(`${indent}buzzer.duty(512)`);
        break;
      case "neopixel_led":
        imports.add("from machine import Pin");
        imports.add("import neopixel");
        setupLines.push(`np = neopixel.NeoPixel(Pin(${d.pin ?? 45}), 1)`);
        {
          const c = d.color ?? "#ff0000";
          const r = parseInt(c.slice(1, 3), 16);
          const g = parseInt(c.slice(3, 5), 16);
          const b = parseInt(c.slice(5, 7), 16);
          const br = (d.brightness ?? 50) / 100;
          chunkLines.push(`${indent}np[0] = (${Math.round(r * br)}, ${Math.round(g * br)}, ${Math.round(b * br)})`);
          chunkLines.push(`${indent}np.write()`);
        }
        break;
      case "neopixel_rgb":
        imports.add("from machine import Pin");
        imports.add("import neopixel");
        setupLines.push(`np = neopixel.NeoPixel(Pin(${d.pin ?? 45}), 1)`);
        {
          const br = (d.brightness ?? 50) / 100;
          chunkLines.push(`${indent}np[0] = (${Math.round((d.red ?? 255) * br)}, ${Math.round((d.green ?? 0) * br)}, ${Math.round((d.blue ?? 0) * br)})`);
          chunkLines.push(`${indent}np.write()`);
        }
        break;

      // ─── Loops ─────────────────────────────────────────────────────────────
      case "forever_loop":
        chunkLines.push(`${indent}while True:`);
        {
          const bodyLines = getLoopBodyLines(nodeId, indentLevel + 1);
          chunkLines.push(...(bodyLines.length > 0 ? bodyLines : [`${indent}    pass`]));
        }
        break;
      case "for_loop":
        chunkLines.push(`${indent}for ${d.variable ?? "i"} in range(${d.start ?? 0}, ${d.end ?? 10}, ${d.step ?? 1}):`);
        {
          const bodyLines = getLoopBodyLines(nodeId, indentLevel + 1);
          chunkLines.push(...(bodyLines.length > 0 ? bodyLines : [`${indent}    pass`]));
        }
        break;
      case "while_loop":
        chunkLines.push(`${indent}while ${d.condition ?? "True"}:`);
        {
          const bodyLines = getLoopBodyLines(nodeId, indentLevel + 1);
          chunkLines.push(...(bodyLines.length > 0 ? bodyLines : [`${indent}    pass`]));
        }
        break;
      case "repeat":
        chunkLines.push(`${indent}for _ in range(${d.times ?? 1}):`);
        {
          const bodyLines = getLoopBodyLines(nodeId, indentLevel + 1);
          chunkLines.push(...(bodyLines.length > 0 ? bodyLines : [`${indent}    pass`]));
        }
        break;
      case "break":
        chunkLines.push(`${indent}break`);
        break;

      // ─── Conditional ───────────────────────────────────────────────────────
      case "if_else":
        chunkLines.push(`${indent}if ${d.left ?? ""} ${d.op ?? "=="} ${d.right ?? 0}:`);
        {
          const trueId = getTargetForHandle("true");
          const trueLines = generateChain(trueId, indentLevel + 1);
          if (trueLines.length > 0) {
            chunkLines.push(...trueLines);
          } else {
            chunkLines.push(`${indent}    pass`);
          }
        }
        chunkLines.push(`${indent}else:`);
        {
          const falseId = getTargetForHandle("false");
          const falseLines = generateChain(falseId, indentLevel + 1);
          if (falseLines.length > 0) {
            chunkLines.push(...falseLines);
          } else {
            chunkLines.push(`${indent}    pass`);
          }
        }
        break;

      // ─── IOT ───────────────────────────────────────────────────────────────
      case "wifi_connect":
        imports.add("import network");
        imports.add("import time");
        chunkLines.push(`${indent}wlan = network.WLAN(network.STA_IF)`);
        chunkLines.push(`${indent}wlan.active(True)`);
        chunkLines.push(`${indent}wlan.connect('${d.ssid ?? "MyWiFi"}', '${d.password ?? "password"}')`);
        chunkLines.push(`${indent}while not wlan.isconnected():`);
        chunkLines.push(`${indent}    time.sleep(0.5)`);
        chunkLines.push(`${indent}print('WiFi connected:', wlan.ifconfig()[0])`);
        break;
      case "http_get":
        imports.add("import urequests");
        chunkLines.push(`${indent}${d.varName ?? "response"} = urequests.get('${d.url ?? "http://example.com"}').text`);
        break;
      case "esp_now_sender":
        imports.add("import espnow");
        imports.add("import network");
        chunkLines.push(`${indent}# ESP NOW Send to ${d.mac ?? "FF:FF:FF:FF:FF:FF"}`);
        chunkLines.push(`${indent}en = espnow.ESPNow()`);
        chunkLines.push(`${indent}en.active(True)`);
        chunkLines.push(`${indent}en.add_peer(b'${d.mac?.replace(/:/g, "\\x") ?? "\\xff\\xff\\xff\\xff\\xff\\xff"}')`);
        chunkLines.push(`${indent}en.send(b'${d.sendData ?? "hello"}')`);
        break;
      case "time_online":
        imports.add("import ntptime");
        imports.add("import time");
        chunkLines.push(`${indent}ntptime.settime()`);
        chunkLines.push(`${indent}${d.varName ?? "time_now"} = time.localtime()`);
        break;

      // ─── Sensor ────────────────────────────────────────────────────────────
      case "ultrasonic":
        imports.add("from machine import Pin");
        imports.add("import time");
        chunkLines.push(`${indent}# Ultrasonic - Trig:${d.trigPin ?? 1} Echo:${d.echoPin ?? 5}`);
        chunkLines.push(`${indent}trig = Pin(${d.trigPin ?? 1}, Pin.OUT)`);
        chunkLines.push(`${indent}echo = Pin(${d.echoPin ?? 5}, Pin.IN)`);
        chunkLines.push(`${indent}trig.value(1); time.sleep_us(10); trig.value(0)`);
        chunkLines.push(`${indent}${d.varName ?? "distance"} = echo.value()`);
        break;
      case "touch_sensor":
        imports.add("from machine import TouchPad, Pin");
        chunkLines.push(`${indent}${d.varName ?? "touch_value"} = TouchPad(Pin(${d.pin ?? 4})).read()`);
        break;
      case "soil_moisture":
        imports.add("from machine import ADC, Pin");
        setupLines.push(`soil_moisture_${d.pin ?? 4} = ADC(Pin(${d.pin ?? 4}))`);
        chunkLines.push(`${indent}${d.varName ?? "value"} = soil_moisture_${d.pin ?? 4}.read_u16()`);
        break;
      case "ir_receiver":
        chunkLines.push(`${indent}# IR Receiver on pin ${d.pin ?? 5}`);
        chunkLines.push(`${indent}${d.varName ?? "ir_cmd"} = 0  # Read from IR receiver`);
        break;
      case "ir_sensor":
        imports.add("from machine import Pin");
        chunkLines.push(`${indent}${d.varName ?? "ir_value"} = Pin(${d.pin ?? 4}, Pin.IN).value()`);
        break;

      // ─── Display ───────────────────────────────────────────────────────────
      case "oled_display":
        imports.add("from machine import I2C, Pin");
        imports.add("import ssd1306");
        setupLines.push(`i2c = I2C(0, scl=Pin(${d.sck ?? 47}), sda=Pin(${d.sda ?? 48}))`);
        setupLines.push(`oled = ssd1306.SSD1306_I2C(128, 64, i2c)`);
        if (d.clearScreen) chunkLines.push(`${indent}oled.fill(0)`);
        chunkLines.push(`${indent}oled.text(${d.text ?? "'Hello world'"}, ${d.left ?? 0}, ${d.top ?? 0})`);
        chunkLines.push(`${indent}oled.show()`);
        break;
      case "seven_seg":
        imports.add("import tm1637");
        imports.add("from machine import Pin");
        setupLines.push(`tm = tm1637.TM1637(clk=Pin(${d.clk ?? 17}), dio=Pin(${d.dio ?? 18}))`);
        chunkLines.push(`${indent}tm.number(${d.number ?? 1234})`);
        break;
      case "servo_motor":
        imports.add("from machine import Pin, PWM");
        setupLines.push(`servos = {}
def rotate_servo(pin_num, angle):
    global servos
    if pin_num not in servos:
        pwm = PWM(Pin(pin_num))
        pwm.freq(50)
        servos[pin_num] = pwm
    pwm = servos[pin_num]

    angle = int(angle)
    angle = max(0, min(180, angle))
    duty = int((angle / 180) * 102 + 26)
    pwm.duty(duty)`);
        {
          const angleVal = d.angle ?? 90;
          chunkLines.push(`${indent}rotate_servo(${d.pin ?? 4}, ${angleVal})`);
        }
        break;
      case "servo_motor_advance":
        imports.add("from machine import Pin, PWM");
        imports.add("import time");
        setupLines.push(`servos = {}
def rotate_servo(pin_num, angle):
    global servos
    if pin_num not in servos:
        pwm = PWM(Pin(pin_num))
        pwm.freq(50)
        servos[pin_num] = pwm
    pwm = servos[pin_num]

    angle = int(angle)
    angle = max(0, min(180, angle))
    duty = int((angle / 180) * 102 + 26)
    pwm.duty(duty)`);
        chunkLines.push(`${indent}# Sweep from ${d.startAngle ?? 0} to ${d.endAngle ?? 90} at speed ${d.speed ?? 50}`);
        chunkLines.push(`${indent}for angle in range(${d.startAngle ?? 0}, ${d.endAngle ?? 90}, ${Math.max(1, Math.round((d.speed ?? 50) / 10))}):`);
        chunkLines.push(`${indent}    rotate_servo(${d.pin ?? 4}, angle)`);
        chunkLines.push(`${indent}    time.sleep_ms(${Math.max(10, 100 - (d.speed ?? 50))})`);
        break;
      case "l298n_motor":
        imports.add("from machine import Pin");
        setupLines.push(`motor_in1 = Pin(${d.in1 ?? 13}, Pin.OUT)`);
        setupLines.push(`motor_in2 = Pin(${d.in2 ?? 21}, Pin.OUT)`);
        setupLines.push(`motor_in3 = Pin(${d.in3 ?? 14}, Pin.OUT)`);
        setupLines.push(`motor_in4 = Pin(${d.in4 ?? 12}, Pin.OUT)`);
        {
          const dir = d.direction ?? "Forward";
          if (dir === "Forward") {
            chunkLines.push(`${indent}motor_in1.value(1); motor_in2.value(0); motor_in3.value(1); motor_in4.value(0)`);
          } else if (dir === "Backward") {
            chunkLines.push(`${indent}motor_in1.value(0); motor_in2.value(1); motor_in3.value(0); motor_in4.value(1)`);
          } else if (dir === "Left") {
            chunkLines.push(`${indent}motor_in1.value(0); motor_in2.value(1); motor_in3.value(1); motor_in4.value(0)`);
          } else if (dir === "Right") {
            chunkLines.push(`${indent}motor_in1.value(1); motor_in2.value(0); motor_in3.value(0); motor_in4.value(1)`);
          } else {
            chunkLines.push(`${indent}motor_in1.value(0); motor_in2.value(0); motor_in3.value(0); motor_in4.value(0)`);
          }
        }
        break;

      // ─── New Sensor Nodes ──────────────────────────────────────────────────
      case "analog_sensor":
        imports.add("from machine import ADC, Pin");
        setupLines.push(`adc_${d.pin ?? 34} = ADC(Pin(${d.pin ?? 34}))`);
        chunkLines.push(`${indent}${d.varName ?? "analog_val"} = adc_${d.pin ?? 34}.read_u16() >> 4  # 12-bit`);
        break;
      case "button_digital_input":
        imports.add("from machine import Pin");
        {
          const pullMode = d.pullup ? "Pin.PULL_UP" : "Pin.PULL_DOWN";
          setupLines.push(`btn_${d.pin ?? 0} = Pin(${d.pin ?? 0}, Pin.IN, ${pullMode})`);
          chunkLines.push(`${indent}${d.varName ?? "btn"} = btn_${d.pin ?? 0}.value()`);
        }
        break;

      // ─── New Display Nodes ─────────────────────────────────────────────────
      case "lcd_16x2":
        imports.add("from machine import I2C, Pin");
        imports.add("import lcd_api, i2c_lcd");
        setupLines.push(`i2c_lcd_bus = I2C(0, scl=Pin(${d.scl ?? 22}), sda=Pin(${d.sda ?? 21}), freq=400000)`);
        setupLines.push(`lcd = i2c_lcd.I2cLcd(i2c_lcd_bus, ${d.address ?? "0x27"}, 2, 16)`);
        chunkLines.push(`${indent}lcd.clear()`);
        chunkLines.push(`${indent}lcd.putstr(${d.line1 ?? "'Hello'"})`);
        chunkLines.push(`${indent}lcd.move_to(0, 1)`);
        chunkLines.push(`${indent}lcd.putstr(${d.line2 ?? "'World'"})`);
        break;

      // ─── New GPIO/Output Nodes ─────────────────────────────────────────────
      case "rgb_led_matrix":
        imports.add("import neopixel");
        imports.add("from machine import Pin");
        setupLines.push(`rgb_matrix = neopixel.NeoPixel(Pin(${d.pin ?? 45}), ${d.ledCount ?? 16})`);
        chunkLines.push(`${indent}# Pattern: ${d.pattern ?? "Chase"} on ${d.ledCount ?? 16} LEDs`);
        chunkLines.push(`${indent}for i in range(len(rgb_matrix)):`);
        chunkLines.push(`${indent}    rgb_matrix[i] = (${Math.round((d.brightness ?? 128))}, 0, 0)`);
        chunkLines.push(`${indent}rgb_matrix.write()`);
        break;
      case "pwm_output":
        imports.add("from machine import Pin, PWM");
        setupLines.push(`pwm_out_${d.pin ?? 2} = PWM(Pin(${d.pin ?? 2}), freq=${d.freq ?? 1000})`);
        chunkLines.push(`${indent}pwm_out_${d.pin ?? 2}.duty(${Math.round(((d.duty ?? 50) / 100) * 1023)})`);
        break;

      // ─── New Motor Nodes ───────────────────────────────────────────────────
      case "dc_motor_single":
        imports.add("from machine import Pin, PWM");
        setupLines.push(`dc_in1 = Pin(${d.in1 ?? 13}, Pin.OUT)`);
        setupLines.push(`dc_in2 = Pin(${d.in2 ?? 14}, Pin.OUT)`);
        setupLines.push(`dc_en = PWM(Pin(${d.enPin ?? 12}), freq=1000)`);
        {
          const dir = d.direction ?? "Forward";
          const speedDuty = Math.round(((d.speed ?? 50) / 100) * 1023);
          if (dir === "Forward") {
            chunkLines.push(`${indent}dc_in1.value(1); dc_in2.value(0); dc_en.duty(${speedDuty})`);
          } else if (dir === "Reverse") {
            chunkLines.push(`${indent}dc_in1.value(0); dc_in2.value(1); dc_en.duty(${speedDuty})`);
          } else if (dir === "Brake") {
            chunkLines.push(`${indent}dc_in1.value(1); dc_in2.value(1); dc_en.duty(0)`);
          } else {
            chunkLines.push(`${indent}dc_in1.value(0); dc_in2.value(0); dc_en.duty(0)  # Coast`);
          }
        }
        break;

      // ─── New Motor / Servo Nodes ───────────────────────────────────────────
      case "servo_controller":
        imports.add("from machine import Pin, PWM");
        setupLines.push(`sc_pwm_${d.pin ?? 4} = PWM(Pin(${d.pin ?? 4}), freq=50)`);
        {
          const pulseMin = d.pulseMin ?? 500;
          const pulseMax = d.pulseMax ?? 2500;
          if (d.mode === "sweep") {
            chunkLines.push(`${indent}import time`);
            chunkLines.push(`${indent}for _a in range(${d.sweepMin ?? 0}, ${d.sweepMax ?? 180}, 1):`);
            chunkLines.push(`${indent}    _duty = int(${pulseMin} + (_a / 180) * (${pulseMax} - ${pulseMin}))`);
            chunkLines.push(`${indent}    sc_pwm_${d.pin ?? 4}.duty_ns(_duty * 1000)`);
            chunkLines.push(`${indent}    time.sleep_ms(${Math.round((d.sweepPeriod ?? 1000) / 180)})`);
          } else {
            chunkLines.push(`${indent}sc_pwm_${d.pin ?? 4}.duty_ns(int((${d.angle ?? 90}/180)*(${pulseMax}-${pulseMin})+${pulseMin})*1000)`);
          }
        }
        break;
      case "multi_motor_controller":
        imports.add("from machine import Pin, PWM");
        chunkLines.push(`${indent}# Multi-Motor Controller (${d.syncMode ? "Sync" : "Independent"} mode)`);
        if (d.syncMode) {
          chunkLines.push(`${indent}# All motors mirror Motor 1: speed=${d.m1speed ?? 50}% dir=${d.m1dir ?? "Forward"}`);
        } else {
          chunkLines.push(`${indent}# M1: ${d.m1speed ?? 50}% ${d.m1dir ?? "Forward"}, M2: ${d.m2speed ?? 50}% ${d.m2dir ?? "Forward"}`);
          chunkLines.push(`${indent}# M3: ${d.m3speed ?? 50}% ${d.m3dir ?? "Forward"}, M4: ${d.m4speed ?? 50}% ${d.m4dir ?? "Forward"}`);
        }
        break;
      case "multi_servo_sequencer":
        imports.add("from machine import Pin, PWM");
        imports.add("import time");
        setupLines.push(`mss_servos = [PWM(Pin(${d.servo1pin ?? 4}), freq=50), PWM(Pin(${d.servo2pin ?? 5}), freq=50), PWM(Pin(${d.servo3pin ?? 6}), freq=50)]`);
        chunkLines.push(`${indent}# Multi-Servo Sequencer — keyframe delay: ${d.keyframeDelay ?? 500}ms, loop: ${d.loop ?? true}`);
        chunkLines.push(`${indent}for _servo in mss_servos:`);
        chunkLines.push(`${indent}    _servo.duty_ns(int((90/180)*(2500-500)+500)*1000)  # center`);
        chunkLines.push(`${indent}    time.sleep_ms(${d.keyframeDelay ?? 500})`);
        break;

      // ─── Comms Nodes ───────────────────────────────────────────────────────
      case "ble_mode":
        imports.add("import bluetooth");
        imports.add("from ble_simple_peripheral import BLESimplePeripheral");
        setupLines.push(`ble = bluetooth.BLE()`);
        setupLines.push(`ble_sp = BLESimplePeripheral(ble, name="${d.deviceName ?? "ESP32-BLE"}")`);
        chunkLines.push(`${indent}${d.varName ?? "ble_cmd"} = None`);
        chunkLines.push(`${indent}if ble_sp.is_connected():`);
        chunkLines.push(`${indent}    ${d.varName ?? "ble_cmd"} = ble_sp.read()`);
        break;
      case "wifi_node":
        imports.add("import network");
        imports.add("import time");
        {
          const wMode = d.mode === "ap" ? "AP" : "STA";
          setupLines.push(`wlan = network.WLAN(network.${wMode}_IF)`);
          setupLines.push(`wlan.active(True)`);
          if (d.mode === "ap") {
            setupLines.push(`wlan.config(essid="${d.ssid ?? "ESP32-AP"}", password="${d.password ?? "password123"}")`);
          } else {
            setupLines.push(`wlan.connect("${d.ssid ?? "MyNetwork"}", "${d.password ?? "password123"}")`);
            setupLines.push(`while not wlan.isconnected(): time.sleep_ms(100)`);
          }
        }
        chunkLines.push(`${indent}${d.varName ?? "ip"} = wlan.ifconfig()[0]`);
        break;

      // ─── Tool Nodes ────────────────────────────────────────────────────────
      case "servo_calibration":
        chunkLines.push(`${indent}# Servo Calibration — compile-time utility only (no runtime code)`);
        break;
      case "i2c_scanner":
        imports.add("from machine import I2C, Pin");
        setupLines.push(`i2c_scan_bus = I2C(0, scl=Pin(${d.scl ?? 22}), sda=Pin(${d.sda ?? 21}))`);
        chunkLines.push(`${indent}i2c_devices = i2c_scan_bus.scan()`);
        chunkLines.push(`${indent}print("I2C devices found:", [hex(x) for x in i2c_devices])`);
        break;

      // ─── Math ──────────────────────────────────────────────────────────────
      case "map_range":
        setupLines.push(`def map_range(x, in_min, in_max, out_min, out_max):
    if in_max == in_min:
        return out_min
    return int((x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min)`);
        chunkLines.push(`${indent}${d.varName ?? "mapped_value"} = map_range(${d.value ?? "value"}, ${d.fromMin ?? 0}, ${d.fromMax ?? 4095}, ${d.toMin ?? 0}, ${d.toMax ?? 180})`);
        break;
      case "random_number":
        imports.add("import random");
        chunkLines.push(`${indent}${d.varName ?? "rand_val"} = random.randint(${d.from ?? 0}, ${d.to ?? 100})`);
        break;

      default:
        chunkLines.push(`${indent}# Unknown node type: ${node.type}`);
    }

    // Follow the sequential bottom handle path
    const nextId = getNextNodeId();
    if (nextId) {
      const nextLines = generateChain(nextId, indentLevel);
      return chunkLines.concat(nextLines);
    }
    return chunkLines;
  }

  // Walk all root nodes in sorted order
  const codeLines: string[] = [];
  for (const root of sortedRoots) {
    const chainLines = generateChain(root.id, 0);
    if (chainLines.length > 0) {
      codeLines.push(...chainLines);
      codeLines.push(""); // add spacer between independent loops/routines
    }
  }

  // Assemble the Python code
  if (imports.size > 0) {
    lines.push(...Array.from(imports));
    lines.push("");
  }
  if (setupLines.length > 0) {
    // Unique the setup lines
    const uniqueSetups = Array.from(new Set(setupLines));
    lines.push(...uniqueSetups);
    lines.push("");
  }
  lines.push(...codeLines);

  // Trim trailing spacer lines
  return lines.join("\n").replace(/\n+$/, "\n");
}
