/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Node, Edge } from "@xyflow/react";

// ─── OLED pixel → MONO_HLSB bytes ─────────────────────────────────────────────
// The node stores pixels as boolean[][] with storedH rows (typically 32 for a
// 128×64 display). Each stored row doubles to fill the real OLED height.
function oledPixelsToMonoHLSB(pixels: boolean[][], oledW: number, oledH: number): Uint8Array {
  const storedH = pixels.length || 1;
  const bytesPerRow = Math.ceil(oledW / 8);
  const buf = new Uint8Array(bytesPerRow * oledH);
  for (let oledRow = 0; oledRow < oledH; oledRow++) {
    const srcRow = Math.min(Math.floor((oledRow / oledH) * storedH), storedH - 1);
    const row = pixels[srcRow] ?? [];
    for (let col = 0; col < oledW; col++) {
      if (row[col]) {
        const byteIdx = oledRow * bytesPerRow + Math.floor(col / 8);
        buf[byteIdx] |= (1 << (7 - (col % 8))); // MONO_HLSB: MSB = leftmost pixel
      }
    }
  }
  return buf;
}

function bytesToPyHex(buf: Uint8Array): string {
  return Array.from(buf).map(b => `\\x${b.toString(16).padStart(2, "0")}`).join("");
}

/**
 * Robust Graph Traversal Code Generator for Kakoon CodeLab.
 * Walks the connected flow starting from root nodes (unconnected/entry points),
 * recursing into loop body and conditional branches, and following sequence lines.
 */
export function generatePythonFromFlow(nodes: Node[], edges: Edge[]): string {
  if (nodes.length === 0) return "# Add nodes to generate code\n";

  const nodeMap = new Map<string, Node>();
  for (const n of nodes) nodeMap.set(n.id, n);

  // Use edges exactly as drawn — no flipping/normalization.
  // Users connect nodes in execution order; the direction is correct by design.

  // Root nodes = nodes that have no incoming flow edges
  // (ignore incoming "true"/"false"/"body" handle edges — those are branch entries, not sequential flow)
  const hasIncomingFlow = new Set<string>();
  for (const e of edges) {
    // An edge pointing INTO a node counts as "has incoming flow" only if it's
    // a plain sequential edge (not a body/true/false branch handle from a loop/conditional)
    const srcHandle = e.sourceHandle ?? "";
    if (srcHandle !== "body" && srcHandle !== "true" && srcHandle !== "false") {
      hasIncomingFlow.add(e.target);
    }
  }
  const rootNodes = nodes.filter((n) => !hasIncomingFlow.has(n.id));
  const sortedRoots = [...rootNodes].sort((a, b) => a.position.y - b.position.y);

  const lines: string[] = ["# Generated by Kakoon CodeLab Node Editor", ""];

  // Collect imports, setups, and one-time helpers
  const imports = new Set<string>();
  const setupLines: string[] = [];
  const setupOnce = new Set<string>(); // dedup helper functions across multiple nodes

  // Board hardware pin maps (shared between codegen cases)
  const SERVO_PIN_MAP: Record<string, number> = { S1: 21, S2: 47, S3: 39, S4: 40 };

  const SERVO_PORT_ORDER = ["S1", "S2", "S3", "S4"] as const;
  const usedServoPorts = new Set<string>();
  const markServoPort = (port: unknown) => {
    if (typeof port === "string" && port in SERVO_PIN_MAP) {
      usedServoPorts.add(port);
    }
  };

  for (const node of nodes) {
    const d: any = node.data || {};
    switch (node.type) {
      case "servo_motor":
      case "servo_motor_advance":
      case "servo_controller":
        markServoPort(d.servoPort ?? "S1");
        break;
      case "multi_servo_sequencer":
        markServoPort(d.s1port ?? "S1");
        markServoPort(d.s2port ?? "S2");
        markServoPort(d.s3port ?? "S3");
        break;
    }
  }

  const buildServoHelperBlock = () => {
    const servoLines = SERVO_PORT_ORDER.map((port) => {
      const pin = SERVO_PIN_MAP[port];
      const name = port.toLowerCase();
      return usedServoPorts.has(port)
        ? `${name} = Servo(${pin})`
        : `_servo_pull_down(${pin})`;
    }).join("\n");

    return `# --- Servo class (600–2400 µs, 50 Hz) ---
class Servo:
    PERIOD = 20000
    def __init__(self, pin, mn=600, mx=2400, lo=0, hi=180):
        self._p = PWM(Pin(pin, Pin.OUT), freq=50)
        self._mn, self._mx, self._lo, self._hi = mn, mx, lo, hi
    def angle(self, deg):
        deg = max(self._lo, min(self._hi, deg))
        us  = self._mn + (self._mx - self._mn) * deg / 180
        self._p.duty_u16(int(us / self.PERIOD * 65535))
    def center(self):  self.angle(90)
    def min_pos(self): self.angle(self._lo)
    def max_pos(self): self.angle(self._hi)

def _servo_pull_down(pin):
    Pin(pin, Pin.IN, Pin.PULL_DOWN)

${servoLines}`;
  };

  const DRV8833_HELPER = `# --- DRV8833 motors (1 PWM + 1 digital per motor) ---
class DRV8833:
    MAX = 65535
    def __init__(self, a_pwm, a_dir, b_pwm, b_dir):
        self.ap, self.ad, self.bp, self.bd = a_pwm, a_dir, b_pwm, b_dir
    def throttle_a(self, t): self._drv(self.ap, self.ad, t)
    def throttle_b(self, t): self._drv(self.bp, self.bd, t)
    def stop_a(self): self.ad.value(0); self.ap.duty_u16(0)
    def stop_b(self): self.bd.value(0); self.bp.duty_u16(0)
    def _drv(self, pwm, d, t):
        d.value(0 if t >= 0 else 1)
        duty = int(abs(t) * self.MAX)
        pwm.duty_u16(duty if t >= 0 else self.MAX - duty)

def _mp(pin): return PWM(Pin(pin, Pin.OUT), freq=40000)
def _dp(pin): return Pin(pin, Pin.OUT)
front = DRV8833(_mp(17), _dp(18), _mp(45), _dp(46))  # FR=a, FL=b (a=right front, b=left front)
rear  = DRV8833(_mp(37), _dp(38), _mp(15), _dp(16))  # RR=a, RL=b (a=right rear, b=left rear)`;

  // Helper: emit a shared helper block only once per script
  const emitOnce = (key: string, code: string) => {
    if (!setupOnce.has(key)) { setupOnce.add(key); setupLines.push(code); }
  };

  const visited = new Set<string>();

  // Loop types that use getLoopBodyLines for their body
  const LOOP_TYPES = ["forever_loop", "for_loop", "while_loop", "repeat"];

  /**
   * Returns the lines for the body of a loop / if-else node.
   *
   * Strategy (in order):
   * 1. If one or more "body" handle edges exist, follow each chain in Y order.
   * 2. Otherwise, collect EVERY directly-connected node below the loop (by Y),
   *    sort them by Y, and generate each one's chain independently — so you can
   *    wire multiple nodes into a loop and they all appear in the body.
   */
  function getLoopBodyLines(loopId: string, indentLevel: number): string[] {
    // 1. Explicit body handle edges (support multiple wires from "body")
    const bodyEdges = edges.filter((e) => e.source === loopId && e.sourceHandle === "body");
    if (bodyEdges.length > 0) {
      const result: string[] = [];
      const targets = bodyEdges
        .map((e) => nodeMap.get(e.target))
        .filter((n): n is Node => !!n)
        .sort((a, b) => a.position.y - b.position.y);
      for (const t of targets) result.push(...generateChain(t.id, indentLevel));
      return result;
    }

    // 2. Fall back: every directly-connected node below the loop node by Y
    const loopNode = nodeMap.get(loopId);
    if (!loopNode) return [];
    const connectedBelow = edges
      .filter((e) => e.source === loopId)
      .map((e) => nodeMap.get(e.target))
      .filter((n): n is Node => !!n && n.position.y > loopNode.position.y)
      .sort((a, b) => a.position.y - b.position.y);

    if (connectedBelow.length === 0) return [];
    // Generate each top-level body node independently so ALL of them are included
    const result: string[] = [];
    for (const bodyNode of connectedBelow) {
      result.push(...generateChain(bodyNode.id, indentLevel));
    }
    return result;
  }

  function generateChain(nodeId: string | null, indentLevel: number): string[] {
    if (!nodeId) return [];
    if (visited.has(nodeId)) return [];
    visited.add(nodeId);

    const node = nodeMap.get(nodeId);
    if (!node) return [];

    const d: any = node.data || {};
    const indent = "    ".repeat(indentLevel);
    const chunkLines: string[] = [];

    // Helper to get ALL connected targets for a handle, sorted by Y position
    const getAllTargetsForHandle = (handleId: string): string[] => {
      return edges
        .filter((e) => e.source === nodeId && e.sourceHandle === handleId)
        .map((e) => nodeMap.get(e.target))
        .filter((n): n is Node => !!n)
        .sort((a, b) => a.position.y - b.position.y)
        .map((n) => n.id);
    };

    // Helper to generate lines for multiple branch targets
    const getBranchLines = (handleId: string, indentLvl: number): string[] => {
      const targets = getAllTargetsForHandle(handleId);
      if (targets.length === 0) return [];
      const result: string[] = [];
      for (const tid of targets) result.push(...generateChain(tid, indentLvl));
      return result;
    };

    // Helper to get next sequential statement connected to standard bottom handle.
    // For loop nodes, skip edges used by getLoopBodyLines (body handle, or the
    // first below-node fallback) so the body isn't also emitted as a sequel.
    const getNextNodeId = () => {
      const isLoopNode = LOOP_TYPES.includes(node.type ?? "");
      const edge = edges.find((e) => {
        if (e.source !== nodeId) return false;
        const handle = e.sourceHandle ?? "";
        if (handle === "body" || handle === "true" || handle === "false") return false;
        // For loops using the Y-fallback body, skip the edge we used as body
        if (isLoopNode && !edges.some((b) => b.source === nodeId && b.sourceHandle === "body")) {
          const tgt = nodeMap.get(e.target);
          if (tgt && tgt.position.y > node.position.y) return false; // this is the body edge
        }
        return true;
      });
      return edge ? edge.target : null;
    };

    if (d.disabled) {
      return generateChain(getNextNodeId(), indentLevel);
    }

    switch (node.type) {
      // ─── General ──────────────────────────────────────────────────────────
      case "print":
        chunkLines.push(`${indent}print(${d.text ?? "'Hello world'"})`);
        break;
      case "sleep":
        imports.add("import time");
        chunkLines.push(`${indent}time.sleep(${d.seconds ?? 1})`);
        break;
      case "variable":
        chunkLines.push(`${indent}${d.name ?? "x"} = ${d.value ?? 0}`);
        break;

      // ─── GPIO Pin / Controls ───────────────────────────────────────────────
      case "gpio_pin":
        imports.add("from machine import Pin");
        setupLines.push(`pin_${d.pin ?? 2} = Pin(${d.pin ?? 2}, Pin.${d.mode ?? "OUT"})`);
        break;
      case "pin_write":
        imports.add("from machine import Pin");
        chunkLines.push(`${indent}pin_${d.pin ?? 4}.value(${d.value ? 1 : 0})`);
        break;
      case "pin_read":
        imports.add("from machine import Pin");
        chunkLines.push(`${indent}${d.varName ?? "value"} = pin_${d.pin ?? 4}.value()`);
        break;
      case "pwm":
        imports.add("from machine import Pin, PWM");
        setupLines.push(`pwm_${d.pin ?? 2} = PWM(Pin(${d.pin ?? 2}), freq=${d.freq ?? 1000})`);
        chunkLines.push(`${indent}pwm_${d.pin ?? 2}.duty(${d.duty ?? 512})`);
        break;
      case "adc":
        imports.add("from machine import ADC, Pin");
        setupLines.push(`adc_${d.pin ?? 34} = ADC(Pin(${d.pin ?? 34}))`);
        chunkLines.push(`${indent}${d.varName ?? "value"} = adc_${d.pin ?? 34}.read_u16()`);
        break;
      case "push_button":
        imports.add("from machine import Pin");
        setupLines.push(`btn_${d.pin ?? 4} = Pin(${d.pin ?? 4}, Pin.IN)`);
        chunkLines.push(`${indent}${d.varName ?? "value"} = btn_${d.pin ?? 4}.value()`);
        break;
      case "buzzer_tone":
        imports.add("from machine import Pin, PWM");
        imports.add("import time");
        setupLines.push(`buzzer = PWM(Pin(${d.pin ?? 46}))`);
        chunkLines.push(`${indent}buzzer.freq(${Number(d.tone ?? 1) * 440})`);
        chunkLines.push(`${indent}buzzer.duty(512)`);
        break;
      case "neopixel_led":
        imports.add("from machine import Pin");
        imports.add("import neopixel");
        setupLines.push(`np = neopixel.NeoPixel(Pin(${d.pin ?? 48}), 1)`);
        {
          const c = d.color ?? "#ff0000";
          const r = parseInt(c.slice(1, 3), 16);
          const g = parseInt(c.slice(3, 5), 16);
          const b = parseInt(c.slice(5, 7), 16);
          const br = (d.brightness ?? 50) / 100;
          chunkLines.push(`${indent}np[0] = (${Math.round(r * br)}, ${Math.round(g * br)}, ${Math.round(b * br)})`);
          chunkLines.push(`${indent}np.write()`);
        }
        break;
      case "neopixel_rgb":
        imports.add("from machine import Pin");
        imports.add("import neopixel");
        setupLines.push(`np = neopixel.NeoPixel(Pin(${d.pin ?? 48}), 1)`);
        {
          const br = (d.brightness ?? 50) / 100;
          chunkLines.push(`${indent}np[0] = (${Math.round((d.red ?? 255) * br)}, ${Math.round((d.green ?? 0) * br)}, ${Math.round((d.blue ?? 0) * br)})`);
          chunkLines.push(`${indent}np.write()`);
        }
        break;

      case "neopixel_designer": {
        imports.add("from machine import Pin");
        imports.add("import neopixel, time");
        const npPin = d.pin ?? 48;
        const npCount = d.ledCount ?? 8;
        const npFps = d.fps ?? 10;
        const npFrames = d.frames as number[][][] | undefined;
        setupLines.push(`np = neopixel.NeoPixel(Pin(${npPin}), ${npCount})`);
        const clampRGB = (v: number) => Math.max(0, Math.min(255, Math.round(v)));
        if (npFrames && npFrames.length > 1) {
          const framesStr = npFrames
            .map(f => `    [${f.map((rgb: number[]) => `(${clampRGB(rgb[0])},${clampRGB(rgb[1])},${clampRGB(rgb[2])})`).join(",")}]`)
            .join(",\n");
          setupLines.push(`_np_frames = [\n${framesStr}\n]`);
          chunkLines.push(`${indent}for _f in _np_frames:`);
          chunkLines.push(`${indent}    for _i, _rgb in enumerate(_f): np[_i] = _rgb`);
          chunkLines.push(`${indent}    np.write()`);
          chunkLines.push(`${indent}    time.sleep_ms(${Math.round(1000 / npFps)})`);
        } else if (npFrames && npFrames.length === 1) {
          for (let i = 0; i < npFrames[0].length && i < npCount; i++) {
            const [r, g, b] = npFrames[0][i];
            chunkLines.push(`${indent}np[${i}] = (${clampRGB(r)},${clampRGB(g)},${clampRGB(b)})`);
          }
          chunkLines.push(`${indent}np.write()`);
        }
        break;
      }

      // ─── Loops ─────────────────────────────────────────────────────────────
      case "forever_loop":
        chunkLines.push(`${indent}while True:`);
        {
          const bodyLines = getLoopBodyLines(nodeId, indentLevel + 1);
          chunkLines.push(...(bodyLines.length > 0 ? bodyLines : [`${indent}    pass`]));
        }
        break;
      case "for_loop":
        chunkLines.push(`${indent}for ${d.variable ?? "i"} in range(${d.start ?? 0}, ${d.end ?? 10}, ${d.step ?? 1}):`);
        {
          const bodyLines = getLoopBodyLines(nodeId, indentLevel + 1);
          chunkLines.push(...(bodyLines.length > 0 ? bodyLines : [`${indent}    pass`]));
        }
        break;
      case "while_loop":
        chunkLines.push(`${indent}while ${d.condition ?? "True"}:`);
        {
          const bodyLines = getLoopBodyLines(nodeId, indentLevel + 1);
          chunkLines.push(...(bodyLines.length > 0 ? bodyLines : [`${indent}    pass`]));
        }
        break;
      case "repeat":
        chunkLines.push(`${indent}for _ in range(${d.times ?? 1}):`);
        {
          const bodyLines = getLoopBodyLines(nodeId, indentLevel + 1);
          chunkLines.push(...(bodyLines.length > 0 ? bodyLines : [`${indent}    pass`]));
        }
        break;
      case "break":
        chunkLines.push(`${indent}break`);
        break;

      // ─── Conditional ───────────────────────────────────────────────────────
      case "if_else":
        chunkLines.push(`${indent}if ${d.left ?? ""} ${d.op ?? "=="} ${d.right ?? 0}:`);
        {
          const trueLines = getBranchLines("true", indentLevel + 1);
          chunkLines.push(...(trueLines.length > 0 ? trueLines : [`${indent}    pass`]));
        }
        chunkLines.push(`${indent}else:`);
        {
          const falseLines = getBranchLines("false", indentLevel + 1);
          chunkLines.push(...(falseLines.length > 0 ? falseLines : [`${indent}    pass`]));
        }
        break;

      // ─── IOT ───────────────────────────────────────────────────────────────
      case "wifi_connect":
        imports.add("import network");
        imports.add("import time");
        chunkLines.push(`${indent}wlan = network.WLAN(network.STA_IF)`);
        chunkLines.push(`${indent}wlan.active(True)`);
        chunkLines.push(`${indent}wlan.connect('${d.ssid ?? "MyWiFi"}', '${d.password ?? "password"}')`);
        chunkLines.push(`${indent}while not wlan.isconnected():`);
        chunkLines.push(`${indent}    time.sleep(0.5)`);
        chunkLines.push(`${indent}print('WiFi connected:', wlan.ifconfig()[0])`);
        break;
      case "http_get":
        imports.add("import urequests");
        chunkLines.push(`${indent}${d.varName ?? "response"} = urequests.get('${d.url ?? "http://example.com"}').text`);
        break;
      case "esp_now_sender":
        imports.add("import espnow");
        imports.add("import network");
        chunkLines.push(`${indent}# ESP NOW Send to ${d.mac ?? "FF:FF:FF:FF:FF:FF"}`);
        chunkLines.push(`${indent}en = espnow.ESPNow()`);
        chunkLines.push(`${indent}en.active(True)`);
        chunkLines.push(`${indent}en.add_peer(b'${d.mac?.replace(/:/g, "\\x") ?? "\\xff\\xff\\xff\\xff\\xff\\xff"}')`);
        chunkLines.push(`${indent}en.send(b'${d.sendData ?? "hello"}')`);
        break;
      case "time_online":
        imports.add("import ntptime");
        imports.add("import time");
        chunkLines.push(`${indent}ntptime.settime()`);
        chunkLines.push(`${indent}${d.varName ?? "time_now"} = time.localtime()`);
        break;

      // ─── Sensor ────────────────────────────────────────────────────────────
      case "imu_sensor": {
        // MPU6050 on SoftI2C SCL=42, SDA=41
        imports.add("from machine import SoftI2C, Pin");
        imports.add("import time, math, struct");
        emitOnce("imu_setup", `# MPU6050 IMU — SCL=42 SDA=41
_i2c_imu = SoftI2C(scl=Pin(42), sda=Pin(41))
_i2c_imu.writeto_mem(0x68, 0x6B, b'\\x00')  # wake up
def _imu_read():
    raw = _i2c_imu.readfrom_mem(0x68, 0x3B, 14)
    ax,ay,az,_,gx,gy,gz = struct.unpack('>7h', raw)
    ax/=16384.0; ay/=16384.0; az/=16384.0
    gx/=131.0;  gy/=131.0;  gz/=131.0
    pitch = math.atan2(ay, math.sqrt(ax*ax+az*az)) * 57.2958
    roll  = math.atan2(-ax, az) * 57.2958
    return ax,ay,az,gx,gy,gz,pitch,roll`);
        const vn = d.varName ?? "imu";
        const mode = d.outputMode ?? "print";
        chunkLines.push(`${indent}${vn}_ax,${vn}_ay,${vn}_az,${vn}_gx,${vn}_gy,${vn}_gz,${vn}_pitch,${vn}_roll = _imu_read()`);
        if (mode === "print" || mode === "both") {
          chunkLines.push(`${indent}print(f"MPU6050,{${vn}_ax:.3f},{${vn}_ay:.3f},{${vn}_az:.3f},{${vn}_gx:.1f},{${vn}_gy:.1f},{${vn}_gz:.1f},{${vn}_pitch:.1f},{${vn}_roll:.1f}")`);
        }
        if (d.loopDelay && d.loopDelay > 0) {
          chunkLines.push(`${indent}time.sleep_ms(${d.loopDelay ?? 100})`);
        }
        break;
      }

      case "ultrasonic":
        imports.add("from machine import Pin");
        imports.add("import time");
        chunkLines.push(`${indent}# Ultrasonic - Trig:${d.trigPin ?? 1} Echo:${d.echoPin ?? 5}`);
        chunkLines.push(`${indent}trig = Pin(${d.trigPin ?? 1}, Pin.OUT)`);
        chunkLines.push(`${indent}echo = Pin(${d.echoPin ?? 5}, Pin.IN)`);
        chunkLines.push(`${indent}trig.value(1); time.sleep_us(10); trig.value(0)`);
        chunkLines.push(`${indent}${d.varName ?? "distance"} = echo.value()`);
        break;
      case "touch_sensor":
        imports.add("from machine import TouchPad, Pin");
        chunkLines.push(`${indent}${d.varName ?? "touch_value"} = TouchPad(Pin(${d.pin ?? 4})).read()`);
        break;
      case "soil_moisture":
        imports.add("from machine import ADC, Pin");
        setupLines.push(`soil_moisture_${d.pin ?? 4} = ADC(Pin(${d.pin ?? 4}))`);
        chunkLines.push(`${indent}${d.varName ?? "value"} = soil_moisture_${d.pin ?? 4}.read_u16()`);
        break;
      case "ir_receiver":
        chunkLines.push(`${indent}# IR Receiver on pin ${d.pin ?? 5}`);
        chunkLines.push(`${indent}${d.varName ?? "ir_cmd"} = 0  # Read from IR receiver`);
        break;
      case "ir_sensor":
        imports.add("from machine import Pin");
        chunkLines.push(`${indent}${d.varName ?? "ir_value"} = Pin(${d.pin ?? 4}, Pin.IN).value()`);
        break;

      case "four_channel_touch":
        imports.add("from machine import TouchPad, Pin");
        chunkLines.push(`${indent}# Four channel touch sensor: ${d.t1 ?? "touch1"}, ${d.t2 ?? "touch2"}, ${d.t3 ?? "touch3"}, ${d.t4 ?? "touch4"}`);
        chunkLines.push(`${indent}${d.t1 ?? "touch1"} = TouchPad(Pin(${d.pin1 ?? 4})).read()`);
        chunkLines.push(`${indent}${d.t2 ?? "touch2"} = TouchPad(Pin(${d.pin2 ?? 5})).read()`);
        chunkLines.push(`${indent}${d.t3 ?? "touch3"} = TouchPad(Pin(${d.pin3 ?? 6})).read()`);
        chunkLines.push(`${indent}${d.t4 ?? "touch4"} = TouchPad(Pin(${d.pin4 ?? 7})).read()`);
        break;

      // ─── Display ───────────────────────────────────────────────────────────
      case "oled_display": {
        // d.driver: false = SH1106 (default), true = SSD1306
        const useSSD = d.driver === true;
        const dLib   = useSSD ? "ssd1306" : "sh1106";
        const dClass = useSSD ? "SSD1306_I2C" : "SH1106_I2C";
        const [oledW, oledH] = d.resolution === "128x32" ? [128, 32] : [128, 64];

        imports.add("from machine import SoftI2C, Pin");
        imports.add(`import ${dLib}`);
        setupLines.push(`i2c = SoftI2C(scl=Pin(${d.sck ?? 36}), sda=Pin(${d.sda ?? 35}))`);
        setupLines.push(`oled = ${dLib}.${dClass}(${oledW}, ${oledH}, i2c)`);

        // Always clear before drawing
        chunkLines.push(`${indent}oled.fill(0)`);

        // Static pixel art (drawn in the node's OLED designer)
        const staticPixels = d.staticPixels as boolean[][] | undefined;
        if (staticPixels && staticPixels.some(row => row.some(v => v))) {
          imports.add("import framebuf");
          const hexStr = bytesToPyHex(oledPixelsToMonoHLSB(staticPixels, oledW, oledH));
          chunkLines.push(`${indent}_fb = framebuf.FrameBuffer(bytearray(b'${hexStr}'), ${oledW}, ${oledH}, framebuf.MONO_HLSB)`);
          chunkLines.push(`${indent}oled.blit(_fb, 0, 0)`);
        }

        // Animation frames
        const animFrames = d.animFrames as boolean[][][] | undefined;
        if (animFrames && animFrames.length > 1) {
          imports.add("import framebuf");
          imports.add("import time");
          const framesStr = animFrames.map(f => {
            const hex = bytesToPyHex(oledPixelsToMonoHLSB(f, oledW, oledH));
            return `b'${hex}'`;
          }).join(", ");
          const fps = typeof d.fps === "number" ? d.fps : 10;
          const delayMs = Math.round(1000 / fps);
          setupLines.push(`_oled_frames = [${framesStr}]`);
          chunkLines.push(`${indent}for _fd in _oled_frames:`);
          chunkLines.push(`${indent}    _fb = framebuf.FrameBuffer(bytearray(_fd), ${oledW}, ${oledH}, framebuf.MONO_HLSB)`);
          chunkLines.push(`${indent}    oled.fill(0); oled.blit(_fb, 0, 0); oled.show()`);
          chunkLines.push(`${indent}    time.sleep_ms(${delayMs})`);
        } else {
          // Text lines
          const line1 = typeof d.line1 === "string" ? d.line1 : "";
          const line2 = typeof d.line2 === "string" ? d.line2 : "";
          if (line1) chunkLines.push(`${indent}oled.text(${JSON.stringify(line1)}, 0, 0)`);
          if (line2) chunkLines.push(`${indent}oled.text(${JSON.stringify(line2)}, 0, 12)`);
          chunkLines.push(`${indent}oled.show()`);
        }
        break;
      }
      case "seven_seg":
        imports.add("import tm1637");
        imports.add("from machine import Pin");
        setupLines.push(`tm = tm1637.TM1637(clk=Pin(${d.clk ?? 17}), dio=Pin(${d.dio ?? 18}))`);
        chunkLines.push(`${indent}tm.number(${d.number ?? 1234})`);
        break;
      // ─── Servo nodes ───────────────────────────────────────────────────────
      case "servo_motor": {
        imports.add("from machine import Pin, PWM");
        emitOnce("servo_class", buildServoHelperBlock());
        const PORT_TO_SV: Record<string, string> = { S1: "s1", S2: "s2", S3: "s3", S4: "s4" };
        const sv1 = PORT_TO_SV[(d.servoPort as string) ?? "S1"] ?? "s1";
        chunkLines.push(`${indent}${sv1}.angle(${d.angle ?? 90})  # ${d.servoPort ?? "S1"}`);
        break;
      }
      case "servo_motor_advance": {
        imports.add("from machine import Pin, PWM");
        imports.add("import time");
        emitOnce("servo_class", buildServoHelperBlock());
        const PORT_TO_SV2: Record<string, string> = { S1: "s1", S2: "s2", S3: "s3", S4: "s4" };
        const sv2     = PORT_TO_SV2[(d.servoPort as string) ?? "S1"] ?? "s1";
        const svStart = d.startAngle ?? 0;
        const svEnd   = d.endAngle ?? 90;
        const svSteps = Math.max(1, d.steps ?? 10);
        const svDelay = Math.max(5, Math.round(200 / (d.speed ?? 50) * 10));
        const svStep  = Math.max(1, Math.round(Math.abs(svEnd - svStart) / svSteps));
        const svDir   = svEnd >= svStart ? 1 : -1;
        chunkLines.push(`${indent}# Sweep ${d.servoPort ?? "S1"}: ${svStart}° → ${svEnd}°`);
        chunkLines.push(`${indent}for _a in range(${svStart}, ${svEnd + svDir}, ${svStep * svDir}):`);
        chunkLines.push(`${indent}    ${sv2}.angle(_a)`);
        chunkLines.push(`${indent}    time.sleep_ms(${svDelay})`);
        break;
      }
      case "l298n_motor":
        // Deprecated — generates a warning comment but still basic code
        imports.add("from machine import Pin");
        chunkLines.push(`${indent}# ⚠️ L298N deprecated — use Multi-Motor Controller for DRV8833`);
        break;

      // ─── New Sensor Nodes ──────────────────────────────────────────────────
      case "analog_sensor":
        imports.add("from machine import ADC, Pin");
        setupLines.push(`adc_${d.pin ?? 34} = ADC(Pin(${d.pin ?? 34}))`);
        chunkLines.push(`${indent}${d.varName ?? "analog_val"} = adc_${d.pin ?? 34}.read_u16() >> 4  # 12-bit`);
        break;
      case "button_digital_input":
        imports.add("from machine import Pin");
        {
          const pullMode = d.pullup ? "Pin.PULL_UP" : "Pin.PULL_DOWN";
          setupLines.push(`btn_${d.pin ?? 0} = Pin(${d.pin ?? 0}, Pin.IN, ${pullMode})`);
          chunkLines.push(`${indent}${d.varName ?? "btn"} = btn_${d.pin ?? 0}.value()`);
        }
        break;

      // ─── New Display Nodes ─────────────────────────────────────────────────
      case "lcd_16x2":
        imports.add("from machine import I2C, Pin");
        imports.add("import lcd_api, i2c_lcd");
        setupLines.push(`i2c_lcd_bus = I2C(0, scl=Pin(${d.scl ?? 22}), sda=Pin(${d.sda ?? 21}), freq=400000)`);
        setupLines.push(`lcd = i2c_lcd.I2cLcd(i2c_lcd_bus, ${d.address ?? "0x27"}, 2, 16)`);
        chunkLines.push(`${indent}lcd.clear()`);
        chunkLines.push(`${indent}lcd.putstr(${d.line1 ?? "'Hello'"})`);
        chunkLines.push(`${indent}lcd.move_to(0, 1)`);
        chunkLines.push(`${indent}lcd.putstr(${d.line2 ?? "'World'"})`);
        break;

      // ─── New GPIO/Output Nodes ─────────────────────────────────────────────
      case "rgb_led_matrix":
        imports.add("import neopixel");
        imports.add("from machine import Pin");
        setupLines.push(`rgb_matrix = neopixel.NeoPixel(Pin(${d.pin ?? 48}), ${d.ledCount ?? 16})`);
        chunkLines.push(`${indent}# Pattern: ${d.pattern ?? "Chase"} on ${d.ledCount ?? 16} LEDs`);
        chunkLines.push(`${indent}for i in range(len(rgb_matrix)):`);
        chunkLines.push(`${indent}    rgb_matrix[i] = (${Math.round((d.brightness ?? 128))}, 0, 0)`);
        chunkLines.push(`${indent}rgb_matrix.write()`);
        break;
      case "pwm_output":
        imports.add("from machine import Pin, PWM");
        setupLines.push(`pwm_out_${d.pin ?? 2} = PWM(Pin(${d.pin ?? 2}), freq=${d.freq ?? 1000})`);
        chunkLines.push(`${indent}pwm_out_${d.pin ?? 2}.duty(${Math.round(((d.duty ?? 50) / 100) * 1023)})`);
        break;

      // ─── Motor nodes ───────────────────────────────────────────────────────
      case "robot_drive": {
        imports.add("from machine import Pin, PWM");
        emitOnce("drv8833_class", `class DRV8833:
    MAX = 65535
    def __init__(self, a_pwm, a_dir, b_pwm, b_dir):
        self.ap, self.ad, self.bp, self.bd = a_pwm, a_dir, b_pwm, b_dir
    def throttle_a(self, t): self._drv(self.ap, self.ad, t)
    def throttle_b(self, t): self._drv(self.bp, self.bd, t)
    def stop_a(self): self.ad.value(0); self.ap.duty_u16(0)
    def stop_b(self): self.bd.value(0); self.bp.duty_u16(0)
    def _drv(self, pwm, d, t):
        d.value(0 if t >= 0 else 1)
        duty = int(abs(t) * self.MAX)
        pwm.duty_u16(duty if t >= 0 else self.MAX - duty)
def _mp(pin): return PWM(Pin(pin, Pin.OUT), freq=40000)
def _dp(pin): return Pin(pin, Pin.OUT)
    front = DRV8833(_mp(17), _dp(18), _mp(45), _dp(46))  # FR=a, FL=b (a=right front, b=left front)
    rear  = DRV8833(_mp(37), _dp(38), _mp(15), _dp(16))  # RR=a, RL=b (a=right rear, b=left rear)`);
        const move = (d.move as string) ?? "forward";
        const t    = ((d.speed ?? 75) / 100).toFixed(2);  // throttle 0.0–1.0
        const ti   = (((d.speed ?? 75) * 0.3) / 100).toFixed(2);  // inner wheel for turns
        chunkLines.push(`${indent}# Robot Drive — ${move}`);
        if (move === "forward") {
          chunkLines.push(`${indent}front.throttle_a(${t}); front.throttle_b(${t}); rear.throttle_a(${t}); rear.throttle_b(${t})`);
        } else if (move === "backward") {
          chunkLines.push(`${indent}front.throttle_a(-${t}); front.throttle_b(-${t}); rear.throttle_a(-${t}); rear.throttle_b(-${t})`);
        } else if (move === "left") {
          chunkLines.push(`${indent}front.throttle_a(${t}); front.throttle_b(${ti}); rear.throttle_a(${t}); rear.throttle_b(${ti})`);
        } else if (move === "right") {
          chunkLines.push(`${indent}front.throttle_a(${ti}); front.throttle_b(${t}); rear.throttle_a(${ti}); rear.throttle_b(${t})`);
        } else if (move === "spin_left") {
          chunkLines.push(`${indent}front.throttle_a(${t}); front.throttle_b(-${t}); rear.throttle_a(${t}); rear.throttle_b(-${t})`);
        } else if (move === "spin_right") {
          chunkLines.push(`${indent}front.throttle_a(-${t}); front.throttle_b(${t}); rear.throttle_a(-${t}); rear.throttle_b(${t})`);
        } else {
          chunkLines.push(`${indent}front.stop_a(); front.stop_b(); rear.stop_a(); rear.stop_b()`);
        }
        break;
      }
      case "dc_motor_single": {
        // Maps node port keys (L1/L2/R1/R2) → DRV8833 object + method
        // L1=FL(front.b), L2=RL(rear.b), R1=FR(front.a), R2=RR(rear.a)
        imports.add("from machine import Pin, PWM");
        emitOnce("drv8833_class", DRV8833_HELPER);
        const portToDRV: Record<string, { obj: string; fn: string }> = {
          L1: { obj: "front", fn: "b" },  // FL
          L2: { obj: "rear",  fn: "b" },  // RL
          R1: { obj: "front", fn: "a" },  // FR
          R2: { obj: "rear",  fn: "a" },  // RR
        };
        const mKey  = (d.motorPort as string) ?? "L1";
        const drv   = portToDRV[mKey] ?? portToDRV["L1"];
        const dir   = d.direction ?? "Forward";
        const speed = d.speed ?? 50;
        const t2    = (speed / 100).toFixed(2);
        if (dir === "Brake" || dir === "Coast") {
          chunkLines.push(`${indent}${drv.obj}.stop_${drv.fn}()  # ${dir}`);
        } else {
          const throttle = dir === "Reverse" ? `-${t2}` : t2;
          chunkLines.push(`${indent}${drv.obj}.throttle_${drv.fn}(${throttle})  # ${mKey} ${dir} ${speed}%`);
        }
        break;
      }
      case "servo_controller": {
        imports.add("from machine import Pin, PWM");
        emitOnce("servo_class", buildServoHelperBlock());
        const PORT_TO_SVC: Record<string, string> = { S1: "s1", S2: "s2", S3: "s3", S4: "s4" };
        const scPort = (d.servoPort as string) ?? "S1";
        const scObj  = PORT_TO_SVC[scPort] ?? "s1";
        const pulseMin = d.pulseMin ?? 600;
        const pulseMax = d.pulseMax ?? 2400;
        if (d.mode === "sweep") {
          imports.add("import time");
          const swMin = d.sweepMin ?? 0;
          const swMax = d.sweepMax ?? 180;
          const stepMs = Math.max(5, Math.round((d.sweepPeriod ?? 1000) / Math.abs(swMax - swMin)));
          chunkLines.push(`${indent}# Sweep ${scPort}: ${swMin}° → ${swMax}°`);
          chunkLines.push(`${indent}for _a in range(${swMin}, ${swMax + 1}, 1):`);
          chunkLines.push(`${indent}    ${scObj}.angle(_a)`);
          chunkLines.push(`${indent}    time.sleep_ms(${stepMs})`);
        } else if (d.mode === "continuous") {
          const spd = d.contSpeed ?? 50;
          const angle = Math.max(0, Math.min(180, 90 + Math.round(spd * 0.9)));
          chunkLines.push(`${indent}${scObj}.angle(${angle})  # continuous ${scPort} speed ${spd}%`);
        } else {
          const pulseRange = pulseMax - pulseMin;
          // Create a custom Servo with user-defined pulse range if different from defaults
          if (pulseMin !== 600 || pulseMax !== 2400) {
            chunkLines.push(`${indent}${scObj} = Servo(${SERVO_PIN_MAP[scPort] ?? 21}, mn=${pulseMin}, mx=${pulseMax})`);
          }
          chunkLines.push(`${indent}${scObj}.angle(${d.angle ?? 90})  # ${scPort} → ${d.angle ?? 90}° (pulse ${Math.round(pulseMin + ((d.angle ?? 90) / 180) * pulseRange)} µs)`);
        }
        break;
      }
      case "multi_motor_controller": {
        imports.add("from machine import Pin, PWM");
        emitOnce("drv8833_class", DRV8833_HELPER);
        // Port → DRV8833 object + method: L1=FL(front.b), L2=RL(rear.b), R1=FR(front.a), R2=RR(rear.a)
        const portToDRVm: Record<string, { obj: string; fn: string }> = {
          L1: { obj: "front", fn: "b" },
          L2: { obj: "rear",  fn: "b" },
          R1: { obj: "front", fn: "a" },
          R2: { obj: "rear",  fn: "a" },
        };
        const makeMotorCall = (port: string, speed: number, dir: string) => {
          const drv = portToDRVm[port] ?? portToDRVm["L1"];
          if (dir === "Brake" || dir === "Coast") return `${drv.obj}.stop_${drv.fn}()`;
          const t = ((dir === "Reverse" ? -speed : speed) / 100).toFixed(2);
          return `${drv.obj}.throttle_${drv.fn}(${t})`;
        };
        if (d.syncMode) {
          const spd = d.l1speed ?? 50;
          const dir = d.l1dir ?? "Forward";
          const calls = ["L1","L2","R1","R2"].map(p => makeMotorCall(p, spd, dir)).join("; ");
          chunkLines.push(`${indent}${calls}  # sync all`);
        } else if (d.pairMode) {
          const lCalls = ["L1","L2"].map(p => makeMotorCall(p, d.leftSpeed ?? 50, d.leftDir ?? "Forward")).join("; ");
          const rCalls = ["R1","R2"].map(p => makeMotorCall(p, d.rightSpeed ?? 50, d.rightDir ?? "Forward")).join("; ");
          chunkLines.push(`${indent}${lCalls}  # left side`);
          chunkLines.push(`${indent}${rCalls}  # right side`);
        } else {
          const ports  = ["L1", "L2", "R1", "R2"] as const;
          const speeds = [d.l1speed ?? 50, d.l2speed ?? 50, d.r1speed ?? 50, d.r2speed ?? 50];
          const dirs   = [d.l1dir ?? "Forward", d.l2dir ?? "Forward", d.r1dir ?? "Forward", d.r2dir ?? "Forward"];
          for (let i = 0; i < 4; i++) {
            chunkLines.push(`${indent}${makeMotorCall(ports[i], speeds[i], dirs[i])}  # ${ports[i]}`);
          }
        }
        break;
      }
      case "multi_servo_sequencer": {
        imports.add("from machine import Pin, PWM");
        imports.add("import time");
        emitOnce("servo_class", buildServoHelperBlock());
        // Map port names to servo object names
        const PORT_TO_MSS: Record<string, string> = { S1: "s1", S2: "s2", S3: "s3", S4: "s4" };
        const mssObj1 = PORT_TO_MSS[(d.s1port as string) ?? "S1"] ?? "s1";
        const mssObj2 = PORT_TO_MSS[(d.s2port as string) ?? "S2"] ?? "s2";
        const mssObj3 = PORT_TO_MSS[(d.s3port as string) ?? "S3"] ?? "s3";
        emitOnce(`mss_list_${mssObj1}_${mssObj2}_${mssObj3}`,
          `_mss = [${mssObj1}, ${mssObj2}, ${mssObj3}]  # sequencer servos`);
        chunkLines.push(`${indent}# Multi-Servo Sequencer`);
        if (d.keyframes && Array.isArray(d.keyframes)) {
          for (const kf of d.keyframes) {
            const angles: number[] = kf.angles ?? [90, 90, 90];
            for (let si = 0; si < Math.min(3, angles.length); si++) {
              chunkLines.push(`${indent}_mss[${si}].angle(${angles[si]})`);
            }
            chunkLines.push(`${indent}time.sleep_ms(${d.keyframeDelay ?? 500})`);
          }
        } else {
          chunkLines.push(`${indent}for _sv in _mss: _sv.center()  # center all`);
          chunkLines.push(`${indent}time.sleep_ms(${d.keyframeDelay ?? 500})`);
        }
        break;
      }

      // ─── Comms Nodes ───────────────────────────────────────────────────────
      case "ble_mode":
        imports.add("import bluetooth");
        imports.add("from ble_simple_peripheral import BLESimplePeripheral");
        setupLines.push(`ble = bluetooth.BLE()`);
        setupLines.push(`ble_sp = BLESimplePeripheral(ble, name="${d.deviceName ?? "ESP32-BLE"}")`);
        chunkLines.push(`${indent}${d.varName ?? "ble_cmd"} = None`);
        chunkLines.push(`${indent}if ble_sp.is_connected():`);
        chunkLines.push(`${indent}    ${d.varName ?? "ble_cmd"} = ble_sp.read()`);
        break;
      case "wifi_node":
        imports.add("import network");
        imports.add("import time");
        {
          const wMode = d.mode === "ap" ? "AP" : "STA";
          setupLines.push(`wlan = network.WLAN(network.${wMode}_IF)`);
          setupLines.push(`wlan.active(True)`);
          if (d.mode === "ap") {
            setupLines.push(`wlan.config(essid="${d.ssid ?? "ESP32-AP"}", password="${d.password ?? "password123"}")`);
          } else {
            setupLines.push(`wlan.connect("${d.ssid ?? "MyNetwork"}", "${d.password ?? "password123"}")`);
            setupLines.push(`while not wlan.isconnected(): time.sleep_ms(100)`);
          }
        }
        chunkLines.push(`${indent}${d.varName ?? "ip"} = wlan.ifconfig()[0]`);
        break;

      case "esp_now_receiver":
        imports.add("import espnow");
        imports.add("import network");
        chunkLines.push(`${indent}# ESP NOW Receive from peer`);
        chunkLines.push(`${indent}en = espnow.ESPNow()`);
        chunkLines.push(`${indent}en.active(True)`);
        chunkLines.push(`${indent}${d.varName ?? "espnow_msg"} = en.recv(1024)`);
        break;

      case "mqtt_node":
        imports.add("import network");
        imports.add("from umqtt.simple import MQTTClient");
        chunkLines.push(`${indent}# MQTT node for topic ${d.topic ?? "sensors/data"}`);
        chunkLines.push(`${indent}mqtt_client = MQTTClient("${d.clientId ?? "kakoon-client"}", "${d.broker ?? "broker.hivemq.com"}")`);
        chunkLines.push(`${indent}mqtt_client.connect()`);
        chunkLines.push(`${indent}mqtt_client.publish(b"${d.topic ?? "sensors/data"}", b"${d.payload ?? "hello"}")`);
        break;

      case "http_client":
        imports.add("import urequests");
        chunkLines.push(`${indent}${d.varName ?? "response"} = urequests.get("${d.url ?? "http://example.com"}").text`);
        break;

      case "serial_monitor":
        chunkLines.push(`${indent}print(${d.value ?? "'Serial monitor output'"})`);
        break;

      case "timer_interval":
        imports.add("import time");
        chunkLines.push(`${indent}_last_tick = time.ticks_ms()`);
        chunkLines.push(`${indent}if time.ticks_diff(time.ticks_ms(), _last_tick) >= ${d.interval ?? 1000}:`);
        chunkLines.push(`${indent}    _last_tick = time.ticks_ms()`);
        chunkLines.push(`${indent}    ${d.varName ?? "timer_fired"} = True`);
        break;

      case "variable_state":
        chunkLines.push(`${indent}# Variable state tracker: ${d.name ?? "state"}`);
        chunkLines.push(`${indent}${d.varName ?? "state"} = ${d.value ?? "None"}`);
        break;

      case "math_transform":
        chunkLines.push(`${indent}${d.varName ?? "result"} = ${d.expression ?? "0"}`);
        break;

      case "deep_sleep":
        imports.add("from machine import deepsleep");
        chunkLines.push(`${indent}deepsleep(${d.durationMs ?? 1000})`);
        break;

      case "ota_update":
        chunkLines.push(`${indent}# OTA update placeholder: ${d.url ?? "configure an update URL"}`);
        break;

      case "sd_card":
        imports.add("from machine import SPI, Pin");
        imports.add("import sdcard");
        chunkLines.push(`${indent}# SD card mount on CS pin ${d.csPin ?? 5}`);
        chunkLines.push(`${indent}spi = SPI(1, sck=Pin(${d.sck ?? 18}), mosi=Pin(${d.mosi ?? 23}), miso=Pin(${d.miso ?? 19}))`);
        chunkLines.push(`${indent}sd = sdcard.SDCard(spi, Pin(${d.csPin ?? 5}))`);
        break;

      case "max7219":
        imports.add("from machine import Pin, SPI");
        imports.add("import max7219");
        chunkLines.push(`${indent}# MAX7219 matrix: ${d.width ?? 8}x${d.height ?? 8}`);
        chunkLines.push(`${indent}spi = SPI(1, baudrate=10000000, polarity=0, phase=0)`);
        chunkLines.push(`${indent}display = max7219.Matrix8x8(spi, Pin(${d.csPin ?? 5}), ${d.width ?? 1}, ${d.height ?? 1})`);
        break;

      case "play_animation":
        chunkLines.push(`${indent}# Play animation: ${d.animationName ?? "default"}`);
        chunkLines.push(`${indent}# Animation frames should be supplied by the runtime or library layer.`);
        break;

      case "show_image":
        chunkLines.push(`${indent}# Show image: ${d.imageName ?? "image"}`);
        chunkLines.push(`${indent}# Image rendering is handled by the display library at runtime.`);
        break;

      // ─── Tool Nodes ────────────────────────────────────────────────────────
      case "servo_calibration":
        chunkLines.push(`${indent}# Servo Calibration — compile-time utility only (no runtime code)`);
        break;
      case "i2c_scanner":
        imports.add("from machine import I2C, Pin");
        setupLines.push(`i2c_scan_bus = I2C(0, scl=Pin(${d.scl ?? 22}), sda=Pin(${d.sda ?? 21}))`);
        chunkLines.push(`${indent}i2c_devices = i2c_scan_bus.scan()`);
        chunkLines.push(`${indent}print("I2C devices found:", [hex(x) for x in i2c_devices])`);
        break;

      // ─── Math ──────────────────────────────────────────────────────────────
      case "map_range":
        setupLines.push(`def map_range(x, in_min, in_max, out_min, out_max):
    if in_max == in_min:
        return out_min
    return int((x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min)`);
        chunkLines.push(`${indent}${d.varName ?? "mapped_value"} = map_range(${d.value ?? "value"}, ${d.fromMin ?? 0}, ${d.fromMax ?? 4095}, ${d.toMin ?? 0}, ${d.toMax ?? 180})`);
        break;
      case "random_number":
        imports.add("import random");
        chunkLines.push(`${indent}${d.varName ?? "rand_val"} = random.randint(${d.from ?? 0}, ${d.to ?? 100})`);
        break;

      default:
        chunkLines.push(`${indent}# Unknown node type: ${node.type}`);
    }

    // Follow the sequential bottom handle path
    const nextId = getNextNodeId();
    if (nextId) {
      const nextLines = generateChain(nextId, indentLevel);
      return chunkLines.concat(nextLines);
    }
    return chunkLines;
  }

  // Walk all root nodes in sorted order
  const codeLines: string[] = [];
  for (const root of sortedRoots) {
    const chainLines = generateChain(root.id, 0);
    if (chainLines.length > 0) {
      codeLines.push(...chainLines);
      codeLines.push(""); // add spacer between independent loops/routines
    }
  }

  // Assemble the Python code
  if (imports.size > 0) {
    lines.push(...Array.from(imports));
    lines.push("");
  }
  if (setupLines.length > 0) {
    // Unique the setup lines
    const uniqueSetups = Array.from(new Set(setupLines));
    lines.push(...uniqueSetups);
    lines.push("");
  }
  lines.push(...codeLines);

  // Trim trailing spacer lines
  return lines.join("\n").replace(/\n+$/, "\n");
}
